"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, FileUp, Loader2, RefreshCw, Star, UserPlus } from "lucide-react";
import { SearchableSelect } from "@/components/searchable-select";

type Employee = { id:string; employee_code:string; name:string };
type Meta = { employees:Employee[] };
type DocumentRow = { id:string; employee_id:string; employee_name:string; title:string; document_type:string; expires_on?:string; file_url?:string };
type Review = { id:string; employee_id:string; employee_name:string; period_start:string; period_end:string; status:string; self_review?:string; manager_review?:string; rating?:string };
type Candidate = { id:string; job_title:string; full_name:string; email:string; stage:string; rating?:string };
type RecruitmentMeta = { roles:{id:string;name:string;slug:string}[]; departments:{id:string;name:string}[]; designations:{id:string;name:string}[] };

async function json<T>(url:string, init?:RequestInit):Promise<T>{
  const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});
  const b=await r.json().catch(()=>null);
  if(!r.ok) throw new Error(b?.detail||`${r.status} ${r.statusText}`);
  return b as T;
}

export default function HROperationsPage(){
  const[meta,setMeta]=useState<Meta|null>(null),[documents,setDocuments]=useState<DocumentRow[]>([]),[reviews,setReviews]=useState<Review[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[recruitment,setRecruitment]=useState<RecruitmentMeta|null>(null);
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
  useEffect(()=>{void load();},[]);
  async function load(){setLoading(true);setError(null);try{const[m,d,p,c,r]=await Promise.all([json<Meta>("/api/hr/meta"),json<DocumentRow[]>("/api/hr/documents"),json<Review[]>("/api/hr/performance"),json<Candidate[]>("/api/hr/candidates"),json<RecruitmentMeta>("/api/hr/recruitment-meta")]);setMeta(m);setDocuments(d);setReviews(p);setCandidates(c);setRecruitment(r);}catch(e){setError(e instanceof Error?e.message:"Unable to load HR operations");}finally{setLoading(false)}}
  const employeeOptions=useMemo(()=>(meta?.employees??[]).map(x=>({value:x.id,label:`${x.employee_code} · ${x.name}`})),[meta]);
  const roleOptions=useMemo(()=>(recruitment?.roles??[]).map(x=>({value:x.id,label:x.name})),[recruitment]);
  const departmentOptions=useMemo(()=>(recruitment?.departments??[]).map(x=>({value:x.id,label:x.name})),[recruitment]);
  const designationOptions=useMemo(()=>(recruitment?.designations??[]).map(x=>({value:x.id,label:x.name})),[recruitment]);

  async function uploadDocument(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError(null);setSuccess(null);try{const fd=new FormData(form);const r=await fetch("/api/hr-documents/upload",{method:"POST",body:fd});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||"Upload failed");form.reset();setSuccess("Employee document uploaded securely.");setDocuments(await json<DocumentRow[]>("/api/hr/documents"));}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setBusy(false)}}
  async function saveReview(id:string,manager_review:string,rating:string,status:string){setBusy(true);setError(null);setSuccess(null);try{await json(`/api/hr/performance/${id}`,{method:"PATCH",body:JSON.stringify({manager_review:manager_review||null,rating:rating?Number(rating):null,status})});setSuccess("Performance review updated.");setReviews(await json<Review[]>("/api/hr/performance"));}catch(e){setError(e instanceof Error?e.message:"Unable to update review");}finally{setBusy(false)}}
  async function convertCandidate(e:FormEvent<HTMLFormElement>,candidateId:string){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setError(null);setSuccess(null);try{const result=await json<{employee_code:string;invite_token:string;email:string}>(`/api/hr/candidates/${candidateId}/convert`,{method:"POST",body:JSON.stringify({role_id:d.get("role_id")||null,department_id:d.get("department_id")||null,designation_id:d.get("designation_id")||null,employee_code:d.get("employee_code")||null})});setSuccess(`Employee invitation created for ${result.email} · ${result.employee_code}. Invite token: ${result.invite_token}`);setCandidates(await json<Candidate[]>("/api/hr/candidates"));}catch(e){setError(e instanceof Error?e.message:"Unable to convert candidate");}finally{setBusy(false)}}

  if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-7 animate-spin text-neutral-400"/></main>;
  return <main className="min-h-screen bg-neutral-100 p-4 sm:p-8 lg:p-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard/hr" className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-neutral-950"><ArrowLeft className="size-4"/>HR Management</Link><h1 className="mt-3 text-3xl font-semibold tracking-tight">HR Operations</h1><p className="mt-2 text-sm text-neutral-500">Secure documents, manager reviews and recruitment onboarding.</p></div><button onClick={()=>void load()} disabled={busy} className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm"><RefreshCw className={`size-4 ${busy?"animate-spin":""}`}/>Refresh</button></header>
    {error?<Notice kind="error" text={error}/>:null}{success?<Notice kind="success" text={success}/>:null}

    <div className="mt-6 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileUp className="size-4"/><h2 className="font-semibold">Secure employee document</h2></div><form onSubmit={uploadDocument} className="mt-4 space-y-4"><SearchableSelect label="Employee" name="employee_id" required options={employeeOptions}/><Field name="title" label="Title" required/><Select name="document_type" label="Type" options={["contract","nid","passport","certificate","visa","work_permit","other"]}/><Field name="reference_number" label="Reference"/><div className="grid gap-3 sm:grid-cols-2"><Field name="issued_on" label="Issued on" type="date"/><Field name="expires_on" label="Expires on" type="date"/></div><label className="block text-sm font-medium">File<input name="file" type="file" required className="mt-2 block w-full rounded-xl border bg-white px-3 py-2 text-sm"/></label><label className="block text-sm font-medium">Notes<textarea name="notes" className="mt-2 min-h-20 w-full rounded-xl border p-3 font-normal"/></label><button disabled={busy} className="h-11 w-full rounded-xl bg-neutral-950 text-sm font-semibold text-white disabled:opacity-50">Upload document</button></form></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Employee documents</h2><div className="mt-4 space-y-3">{documents.length?documents.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-medium">{x.employee_name} · {x.title}</p><p className="mt-1 text-xs text-neutral-500">{x.document_type.replaceAll("_"," ")} · expiry {x.expires_on||"N/A"}</p></div>{x.file_url?<a href={`/api/hr-documents/${x.id}/file`} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-1.5 text-xs font-medium">Open secure file</a>:null}</div>):<Empty/>}</div></section>
    </div>

    <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Star className="size-4"/><h2 className="font-semibold">Manager performance reviews</h2></div><div className="mt-4 grid gap-4 xl:grid-cols-2">{reviews.length?reviews.map(x=><ReviewCard key={x.id} row={x} busy={busy} save={saveReview}/>):<Empty/>}</div></section>

    <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UserPlus className="size-4"/><h2 className="font-semibold">Candidate → Employee onboarding</h2></div><p className="mt-1 text-xs text-neutral-500">Uses the existing audited Employee Invitation flow; it does not create a duplicate onboarding path.</p><div className="mt-4 grid gap-4 xl:grid-cols-2">{candidates.filter(x=>x.stage!=="hired"&&x.stage!=="rejected").length?candidates.filter(x=>x.stage!=="hired"&&x.stage!=="rejected").map(x=><form key={x.id} onSubmit={e=>void convertCandidate(e,x.id)} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{x.full_name}</p><p className="text-xs text-neutral-500">{x.job_title} · {x.email}</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] uppercase">{x.stage}</span></div><div className="mt-4 space-y-3"><SearchableSelect label="Role" name="role_id" options={roleOptions}/><SearchableSelect label="Department" name="department_id" options={departmentOptions}/><SearchableSelect label="Designation" name="designation_id" options={designationOptions}/><Field name="employee_code" label="Employee code (optional)"/><button disabled={busy} className="h-10 w-full rounded-xl bg-neutral-950 text-sm font-semibold text-white disabled:opacity-50">Create employee invitation</button></div></form>):<Empty/>}</div></section>
  </div></main>;
}

function ReviewCard({row,busy,save}:{row:Review;busy:boolean;save:(id:string,review:string,rating:string,status:string)=>Promise<void>}){const[review,setReview]=useState(row.manager_review||"");const[rating,setRating]=useState(row.rating||"");const[status,setStatus]=useState(row.status||"draft");return <div className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{row.employee_name}</p><p className="text-xs text-neutral-500">{row.period_start} — {row.period_end}</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] uppercase">{row.status}</span></div>{row.self_review?<div className="mt-3 rounded-lg bg-neutral-50 p-3 text-sm"><strong>Self review:</strong> {row.self_review}</div>:null}<label className="mt-3 block text-sm font-medium">Manager review<textarea value={review} onChange={e=>setReview(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Rating (0–5)<input value={rating} onChange={e=>setRating(e.target.value)} min="0" max="5" step="0.1" type="number" className="mt-2 h-10 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-medium">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 h-10 w-full rounded-xl border px-3 font-normal"><option value="draft">Draft</option><option value="in_review">In review</option><option value="completed">Completed</option></select></label></div><button disabled={busy} onClick={()=>void save(row.id,review,rating,status)} className="mt-3 h-10 w-full rounded-xl border text-sm font-medium disabled:opacity-50">Save manager review</button></div>}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="block text-sm font-medium">{label}<input name={name} type={type} required={required} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <label className="block text-sm font-medium">{label}<select name={name} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal">{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
function Empty(){return <div className="rounded-xl border border-dashed py-10 text-center text-sm text-neutral-400">No records yet.</div>}
function Notice({kind,text}:{kind:"error"|"success";text:string}){return <div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${kind==="error"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{text}</div>}
