"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, CalendarDays, HandCoins, Plus, Search, WalletCards } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";
import { CurrencySelect } from "@/components/currency-select";
import { FinancialConfirmationDialog } from "@/components/financial-confirmation-dialog";
import { MoneyInput } from "@/components/money-input";
import { SearchableSelect } from "@/components/searchable-select";
import { confirmDiscardChanges, useUnsavedChanges } from "@/hooks/use-unsaved-changes";
import { getApiErrorMessage } from "@/lib/api-error";

type Loan = { id: string; lender_name: string; lender_type: string; currency: string; approved_amount: string; disbursed_amount: string; undisbursed_amount: string; outstanding_principal: string; annual_interest_rate: string; approval_date: string; maturity_date: string | null; status: string; reference: string | null; notes?: string | null };
type FinancialAccount = { id: string; name: string; account_type: string; currency: string; current_balance: string };
type ScheduleItem = { id: string; installment_number: number; due_date: string; principal_due: string; interest_due: string; fee_due: string; principal_paid: string; interest_paid: string; fee_paid: string; status: string };
type Disbursement = { id: string; date: string; account_name: string; principal_amount: string; fee_withheld_amount: string; net_received_amount: string; reference: string | null; notes: string | null };
type Repayment = { id: string; date: string; account_name: string; principal_amount: string; interest_amount: string; reference: string | null; notes: string | null };
type LoanFee = { id: string; date: string; fee_type: string; amount: string; payment_status: string; reference: string | null; notes: string | null };
type LoanHistory = { disbursements: Disbursement[]; repayments: Repayment[]; fees: LoanFee[] };
type Mode = "new" | "receive" | "repay" | null;

function amount(value: string | number, currency?: string) { return `${currency ? `${currency} ` : ""}${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function today() { return new Date().toISOString().slice(0, 10); }
function overdue(date: string, status: string) { return Boolean(date && status !== "paid" && date < today()); }
const blankApprove=()=>({ lender_name: "", lender_type: "bank", currency: "BDT", approved_amount: "", annual_interest_rate: "0", approval_date: today(), maturity_date: "", reference: "", notes: "" });
const blankReceive=()=>({ account_id: "", disbursement_date: today(), principal_amount: "", fee_withheld_amount: "0", reference: "", notes: "" });
const blankRepay=()=>({ account_id: "", payment_date: today(), principal_amount: "", interest_amount: "0", fee_amount: "0", fee_type: "loan_fee", reference: "", notes: "" });

export default function LoanAccountingPage() {
  const [loans, setLoans] = useState<Loan[]>([]);
  const [accounts, setAccounts] = useState<FinancialAccount[]>([]);
  const [schedule, setSchedule] = useState<ScheduleItem[]>([]);
  const [history, setHistory] = useState<LoanHistory>({ disbursements: [], repayments: [], fees: [] });
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedLoanId, setSelectedLoanId] = useState("");
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [mode, setMode] = useState<Mode>(null);
  const [confirmMode,setConfirmMode]=useState<Mode>(null);
  const [approve, setApprove] = useState(blankApprove());
  const [receive, setReceive] = useState(blankReceive());
  const [repay, setRepay] = useState(blankRepay());

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const [loanResponse, accountResponse] = await Promise.all([fetch("/api/accounting/loans", { cache: "no-store" }), fetch("/api/finance/accounts", { cache: "no-store" })]);
      const [loanPayload, accountPayload] = await Promise.all([loanResponse.json(), accountResponse.json()]);
      if (!loanResponse.ok) throw new Error(getApiErrorMessage(loanPayload, "Could not load loans"));
      if (!accountResponse.ok) throw new Error(getApiErrorMessage(accountPayload, "Could not load accounts"));
      setLoans(loanPayload); setAccounts(accountPayload);
      setSelectedLoanId((current) => current && loanPayload.some((x: Loan) => x.id === current) ? current : loanPayload[0]?.id || "");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load loans"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const loadDetail = useCallback(async (loanId: string) => {
    if (!loanId) { setSchedule([]); setHistory({ disbursements: [], repayments: [], fees: [] }); return; }
    setDetailLoading(true);
    try {
      const [scheduleResponse, historyResponse] = await Promise.all([fetch(`/api/accounting/loans/${loanId}/schedule`, { cache: "no-store" }), fetch(`/api/accounting/loans/${loanId}/history`, { cache: "no-store" })]);
      const [schedulePayload, historyPayload] = await Promise.all([scheduleResponse.json(), historyResponse.json()]);
      if (!scheduleResponse.ok) throw new Error(getApiErrorMessage(schedulePayload, "Could not load repayment schedule"));
      if (!historyResponse.ok) throw new Error(getApiErrorMessage(historyPayload, "Could not load loan history"));
      setSchedule(schedulePayload); setHistory(historyPayload);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load loan details"); }
    finally { setDetailLoading(false); }
  }, []);
  useEffect(() => { void loadDetail(selectedLoanId); }, [selectedLoanId, loadDetail]);

  const selected = useMemo(() => loans.find((loan) => loan.id === selectedLoanId) ?? null, [loans, selectedLoanId]);
  const filteredLoans = useMemo(() => { const q = query.trim().toLowerCase(); return loans.filter((loan) => (!q || `${loan.lender_name} ${loan.reference ?? ""} ${loan.currency} ${loan.status}`.toLowerCase().includes(q)) && (statusFilter === "all" || loan.status === statusFilter)); }, [loans, query, statusFilter]);
  const compatibleAccounts = useMemo(() => selected ? accounts.filter((account) => account.currency === selected.currency) : accounts, [accounts, selected]);
  const accountOptions = useMemo(() => compatibleAccounts.map((account) => ({ value: account.id, label: `${account.name} · ${amount(account.current_balance, account.currency)}`, keywords: `${account.name} ${account.currency} ${account.account_type}` })), [compatibleAccounts]);
  const nextInstallment = useMemo(() => schedule.find((item) => item.status !== "paid") ?? null, [schedule]);
  const totalInterestPaid = useMemo(() => history.repayments.reduce((sum, item) => sum + Number(item.interest_amount || 0), 0), [history.repayments]);
  const totalFees = useMemo(() => history.fees.reduce((sum, item) => sum + Number(item.amount || 0), 0), [history.fees]);
  const receiveAccount=accounts.find(a=>a.id===receive.account_id)??null;
  const repayAccount=accounts.find(a=>a.id===repay.account_id)??null;
  const approveDirty=mode==="new"&&Boolean(approve.lender_name||approve.approved_amount||approve.reference||approve.notes||approve.maturity_date||Number(approve.annual_interest_rate||0)>0);
  const receiveDirty=mode==="receive"&&Boolean(receive.account_id||receive.principal_amount||receive.reference||receive.notes||Number(receive.fee_withheld_amount||0)>0);
  const repayDirty=mode==="repay"&&Boolean(repay.account_id||repay.principal_amount||Number(repay.interest_amount||0)>0||Number(repay.fee_amount||0)>0||repay.reference||repay.notes);
  const dirty=approveDirty||receiveDirty||repayDirty;
  useUnsavedChanges(dirty&&!saving);

  function closeMode(){if(!confirmDiscardChanges(dirty,"Discard this unposted loan form?"))return;setMode(null);setConfirmMode(null)}
  function chooseLoan(id:string){if(!confirmDiscardChanges(dirty,"Switch loans and discard this unposted form?"))return;setSelectedLoanId(id);setMode(null);setConfirmMode(null)}
  function reviewApprove(e:FormEvent){e.preventDefault();setError(null);setConfirmMode("new")}
  function reviewReceive(e:FormEvent){e.preventDefault();if(selected)setConfirmMode("receive")}
  function reviewRepay(e:FormEvent){e.preventDefault();if(selected)setConfirmMode("repay")}

  async function postApprove() {
    setSaving(true); setError(null);
    try { const response = await fetch("/api/accounting/loans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...approve, approved_amount: Number(approve.approved_amount), annual_interest_rate: Number(approve.annual_interest_rate || 0), maturity_date: approve.maturity_date || null, reference: approve.reference || null, notes: approve.notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(getApiErrorMessage(payload, "Could not record loan agreement")); setApprove(blankApprove());setConfirmMode(null);await load();setSelectedLoanId(payload.id);setMode(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not record loan agreement");setConfirmMode(null); }
    finally { setSaving(false); }
  }
  async function postReceive() {
    if (!selected) return; setSaving(true); setError(null);
    try { const response = await fetch(`/api/accounting/loans/${selected.id}/disburse`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...receive, principal_amount: Number(receive.principal_amount), fee_withheld_amount: Number(receive.fee_withheld_amount || 0), reference: receive.reference || null, notes: receive.notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(getApiErrorMessage(payload, "Could not receive loan money")); setReceive(blankReceive());setConfirmMode(null);await load();await loadDetail(selected.id);setMode(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not receive loan money");setConfirmMode(null); }
    finally { setSaving(false); }
  }
  async function postRepay() {
    if (!selected) return; setSaving(true); setError(null);
    try { const response = await fetch(`/api/accounting/loans/${selected.id}/repay`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...repay, principal_amount: Number(repay.principal_amount || 0), interest_amount: Number(repay.interest_amount || 0), fee_amount: Number(repay.fee_amount || 0), reference: repay.reference || null, notes: repay.notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(getApiErrorMessage(payload, "Could not record repayment")); setRepay(blankRepay());setConfirmMode(null);await load();await loadDetail(selected.id);setMode(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not record repayment");setConfirmMode(null); }
    finally { setSaving(false); }
  }

  const approvalDetails=[{label:"Lender",value:approve.lender_name||"—"},{label:"Approved amount",value:amount(approve.approved_amount||0,approve.currency),emphasis:true},{label:"Annual interest",value:`${approve.annual_interest_rate||0}%`},{label:"Approval date",value:approve.approval_date},{label:"Maturity",value:approve.maturity_date||"Not set"},...(approve.reference?[{label:"Reference",value:approve.reference}]:[])];
  const receiveDetails=selected?[{label:"Loan",value:selected.lender_name},{label:"Approved but not received",value:amount(selected.undisbursed_amount,selected.currency)},{label:"Principal disbursed",value:amount(receive.principal_amount||0,selected.currency),emphasis:true},{label:"Fee withheld",value:amount(receive.fee_withheld_amount||0,selected.currency)},{label:"Net cash received",value:amount(Math.max(0,Number(receive.principal_amount||0)-Number(receive.fee_withheld_amount||0)),selected.currency),emphasis:true},{label:"Receive into",value:receiveAccount?.name||"—"},{label:"Date",value:receive.disbursement_date}]:[];
  const repayTotal=Number(repay.principal_amount||0)+Number(repay.interest_amount||0)+Number(repay.fee_amount||0);
  const repayDetails=selected?[{label:"Loan",value:selected.lender_name},{label:"Principal currently due",value:amount(selected.outstanding_principal,selected.currency)},{label:"Principal part",value:amount(repay.principal_amount||0,selected.currency)},{label:"Interest part",value:amount(repay.interest_amount||0,selected.currency)},{label:"Fee part",value:amount(repay.fee_amount||0,selected.currency)},{label:"Total payment",value:amount(repayTotal,selected.currency),emphasis:true},{label:"Pay from",value:repayAccount?.name||"—"},{label:"Date",value:repay.payment_date}]:[];

  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Business loans</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Agreement, money received, repayments and schedules stay together in one loan record.</p></div><button onClick={() => {if(!confirmDiscardChanges(dirty))return;setApprove(blankApprove());setMode("new");setConfirmMode(null)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white"><Plus className="size-4" />New loan agreement</button></div>
    <AccountingNav />
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}

    <section className="grid gap-4 lg:grid-cols-[340px_minmax(0,1fr)]">
      <div className="rounded-2xl border bg-white p-3"><div className="px-2 py-2"><h2 className="font-semibold">Your loans</h2><p className="mt-1 text-xs text-neutral-400">Search and select a loan to inspect the full lifecycle.</p></div><div className="mt-3 space-y-2"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-neutral-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search lender or reference…" className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)} className="w-full rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="approved">Approved</option><option value="active">Active</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select></div><div className="mt-3 max-h-[650px] space-y-2 overflow-y-auto">{filteredLoans.map((loan) => <button key={loan.id} type="button" onClick={() => chooseLoan(loan.id)} className={`w-full rounded-xl border p-4 text-left transition ${selectedLoanId === loan.id ? "border-neutral-950 bg-neutral-950 text-white" : "bg-white hover:bg-neutral-50"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{loan.lender_name}</p><p className={`mt-1 text-xs ${selectedLoanId === loan.id ? "text-neutral-300" : "text-neutral-400"}`}>{loan.reference || `${loan.currency} loan`}</p></div><span className={`rounded-full px-2 py-1 text-[11px] capitalize ${selectedLoanId === loan.id ? "bg-white/10" : "bg-neutral-100 text-neutral-500"}`}>{loan.status}</span></div><p className="mt-4 text-lg font-semibold">{amount(loan.outstanding_principal, loan.currency)} due</p></button>)}{!loading && filteredLoans.length === 0 ? <div className="rounded-xl border border-dashed p-6 text-center"><HandCoins className="mx-auto size-7 text-neutral-300" /><p className="mt-3 text-sm font-medium">No matching loans</p></div> : null}</div></div>

      <div className="space-y-4">{selected ? <>
        <div className="rounded-2xl border bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-neutral-500">Loan from</p><h2 className="mt-1 text-2xl font-semibold">{selected.lender_name}</h2><p className="mt-1 text-sm text-neutral-400">{selected.currency} · {selected.annual_interest_rate}% annual interest{selected.maturity_date ? ` · Maturity ${selected.maturity_date}` : ""}</p>{selected.notes ? <p className="mt-3 max-w-2xl text-sm text-neutral-500">{selected.notes}</p> : null}</div><div className="flex flex-wrap gap-2"><button type="button" disabled={Number(selected.undisbursed_amount) <= 0} onClick={() => {if(!confirmDiscardChanges(dirty))return;setReceive(blankReceive());setMode("receive");setConfirmMode(null)}} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-medium disabled:opacity-40"><ArrowDownToLine className="size-4" />Receive money</button><button type="button" disabled={Number(selected.outstanding_principal) <= 0} onClick={() => {if(!confirmDiscardChanges(dirty))return;setRepay(blankRepay());setMode("repay");setConfirmMode(null)}} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-3 py-2 text-sm font-medium text-white disabled:opacity-40"><WalletCards className="size-4" />Make repayment</button></div></div>
          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Loan agreement" value={amount(selected.approved_amount, selected.currency)} help="Maximum approved" /><Stat label="Money received" value={amount(selected.disbursed_amount, selected.currency)} help="Actually received" /><Stat label="Principal due" value={amount(selected.outstanding_principal, selected.currency)} help="Still owed" /><Stat label="Interest + fees paid" value={amount(totalInterestPaid + totalFees, selected.currency)} help="Tracked separately" /></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><Stat label="Next installment" value={nextInstallment ? amount(Number(nextInstallment.principal_due)+Number(nextInstallment.interest_due)+Number(nextInstallment.fee_due), selected.currency) : "No schedule"} help={nextInstallment ? `Due ${nextInstallment.due_date}${overdue(nextInstallment.due_date,nextInstallment.status)?" · OVERDUE":""}` : "No repayment schedule recorded"}/><Stat label="Reference" value={selected.reference || "—"} help={`Approved ${selected.approval_date}`} /></div>
        </div>
        <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Repayment schedule</h3><p className="mt-1 text-sm text-neutral-500">Installments, paid amounts and overdue status.</p></div><CalendarDays className="size-5 text-neutral-300"/></div>{detailLoading ? <p className="mt-4 text-sm text-neutral-400">Loading schedule…</p> : schedule.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="py-3 pr-4">#</th><th className="py-3 pr-4">Due</th><th className="py-3 pr-4">Principal</th><th className="py-3 pr-4">Interest</th><th className="py-3 pr-4">Fees</th><th className="py-3">Status</th></tr></thead><tbody>{schedule.map((item)=><tr key={item.id} className="border-b last:border-0"><td className="py-3 pr-4 font-medium">{item.installment_number}</td><td className={`py-3 pr-4 ${overdue(item.due_date,item.status)?"font-medium text-red-600":""}`}>{item.due_date}</td><td className="py-3 pr-4">{amount(item.principal_due,selected.currency)}<p className="text-xs text-neutral-400">Paid {amount(item.principal_paid,selected.currency)}</p></td><td className="py-3 pr-4">{amount(item.interest_due,selected.currency)}<p className="text-xs text-neutral-400">Paid {amount(item.interest_paid,selected.currency)}</p></td><td className="py-3 pr-4">{amount(item.fee_due,selected.currency)}<p className="text-xs text-neutral-400">Paid {amount(item.fee_paid,selected.currency)}</p></td><td className="py-3 capitalize">{overdue(item.due_date,item.status)?"overdue":item.status}</td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-xl border border-dashed p-6 text-center text-sm text-neutral-400">No repayment schedule has been recorded.</div>}</div>
        <div className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">Loan history</h3><p className="mt-1 text-sm text-neutral-500">Every receipt, repayment and fee stays traceable.</p>{detailLoading ? <p className="mt-4 text-sm text-neutral-400">Loading history…</p> : <div className="mt-4 space-y-3">{history.disbursements.map((item)=><HistoryRow key={`d-${item.id}`} title="Money received" date={item.date} meta={`${item.account_name} · Principal ${amount(item.principal_amount,selected.currency)} · Net ${amount(item.net_received_amount,selected.currency)}${Number(item.fee_withheld_amount)>0?` · Fee ${amount(item.fee_withheld_amount,selected.currency)}`:""}`} reference={item.reference} notes={item.notes}/>)}{history.repayments.map((item)=><HistoryRow key={`r-${item.id}`} title="Repayment" date={item.date} meta={`${item.account_name} · Principal ${amount(item.principal_amount,selected.currency)} · Interest ${amount(item.interest_amount,selected.currency)}`} reference={item.reference} notes={item.notes}/>)}{history.fees.map((item)=><HistoryRow key={`f-${item.id}`} title={`Fee · ${item.fee_type.replaceAll("_"," ")}`} date={item.date} meta={`${amount(item.amount,selected.currency)} · ${item.payment_status}`} reference={item.reference} notes={item.notes}/>)}{!history.disbursements.length&&!history.repayments.length&&!history.fees.length?<div className="rounded-xl border border-dashed p-6 text-center text-sm text-neutral-400">No money movement recorded for this loan yet.</div>:null}</div>}<div className="mt-5 rounded-xl border bg-neutral-50 p-4 text-sm text-neutral-500"><p className="font-medium text-neutral-900">Posted loan history</p><p className="mt-1">Disbursements and repayments affect ledgers and should be corrected through controlled reversal/correction, not silent edits.</p></div></div>
      </> : <div className="rounded-2xl border border-dashed bg-white p-12 text-center"><HandCoins className="mx-auto size-9 text-neutral-300" /><p className="mt-3 font-medium">Select or create a loan</p></div>}</div>
    </section>

    {mode ? <section className="rounded-2xl border bg-white p-5"><div className="mb-5"><h2 className="text-lg font-semibold">{mode === "new" ? "Record a new loan agreement" : mode === "receive" ? "Receive loan money" : "Record a loan repayment"}</h2><p className="mt-1 text-sm text-neutral-500">{mode === "new" ? "Agreement only; no bank balance changes yet." : mode === "receive" ? "Choose where the lender actually sent the money. Nothing posts until review." : "Split the real payment into principal, interest and fees. Nothing posts until review."}</p></div>
      {mode === "new" ? <form onSubmit={reviewApprove} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Lender name"><input required value={approve.lender_name} onChange={(event) => setApprove((current) => ({ ...current, lender_name: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Lender type"><select value={approve.lender_type} onChange={(event) => setApprove((current) => ({ ...current, lender_type: event.target.value }))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="bank">Bank</option><option value="person">Person</option><option value="company">Company</option><option value="investor">Investor</option><option value="other">Other</option></select></Field><CurrencySelect required clearable={false} value={approve.currency} onValueChange={(value) => setApprove((current) => ({ ...current, currency: value }))} /><MoneyInput label="Approved amount" currency={approve.currency} required min={0.01} value={approve.approved_amount} onValueChange={(value) => setApprove((current) => ({ ...current, approved_amount: value }))} /><Field label="Annual interest %"><input type="number" min="0" step="0.0001" value={approve.annual_interest_rate} onChange={(event) => setApprove((current) => ({ ...current, annual_interest_rate: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Agreement / approval date"><input required type="date" value={approve.approval_date} onChange={(event) => setApprove((current) => ({ ...current, approval_date: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Maturity date"><input type="date" value={approve.maturity_date} onChange={(event) => setApprove((current) => ({ ...current, maturity_date: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Reference"><input value={approve.reference} onChange={(event) => setApprove((current) => ({ ...current, reference: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><div className="flex items-end gap-2"><button disabled={saving} className="flex-1 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Review agreement</button><button type="button" onClick={closeMode} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button></div></form> : null}
      {mode === "receive" && selected ? <form onSubmit={reviewReceive} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><SearchableSelect label="Receive into" required clearable={false} value={receive.account_id} onValueChange={(value) => setReceive((current) => ({ ...current, account_id: value }))} options={accountOptions} placeholder="Select bank/cash/wallet" searchPlaceholder="Search account..." /><MoneyInput label="Amount lender disbursed" currency={selected.currency} required min={0.01} max={Number(selected.undisbursed_amount)} value={receive.principal_amount} onValueChange={(value) => setReceive((current) => ({ ...current, principal_amount: value }))} hint={`Still available: ${amount(selected.undisbursed_amount, selected.currency)}`} /><MoneyInput label="Fee deducted before receiving" currency={selected.currency} min={0} value={receive.fee_withheld_amount} onValueChange={(value) => setReceive((current) => ({ ...current, fee_withheld_amount: value }))} /><Field label="Date received"><input required type="date" value={receive.disbursement_date} onChange={(event) => setReceive((current) => ({ ...current, disbursement_date: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Reference"><input value={receive.reference} onChange={(event) => setReceive((current) => ({ ...current, reference: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><div className="flex items-end gap-2"><button className="flex-1 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white">Review money received</button><button type="button" onClick={closeMode} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button></div></form> : null}
      {mode === "repay" && selected ? <form onSubmit={reviewRepay} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><SearchableSelect label="Pay from" required clearable={false} value={repay.account_id} onValueChange={(value) => setRepay((current) => ({ ...current, account_id: value }))} options={accountOptions} placeholder="Select bank/cash/wallet" searchPlaceholder="Search account..." /><MoneyInput label="Principal part" currency={selected.currency} min={0} max={Number(selected.outstanding_principal)} value={repay.principal_amount} onValueChange={(value) => setRepay((current) => ({ ...current, principal_amount: value }))} hint={`Principal still due: ${amount(selected.outstanding_principal, selected.currency)}`} /><MoneyInput label="Interest part" currency={selected.currency} min={0} value={repay.interest_amount} onValueChange={(value) => setRepay((current) => ({ ...current, interest_amount: value }))} /><MoneyInput label="Other loan fee" currency={selected.currency} min={0} value={repay.fee_amount} onValueChange={(value) => setRepay((current) => ({ ...current, fee_amount: value }))} /><Field label="Payment date"><input required type="date" value={repay.payment_date} onChange={(event) => setRepay((current) => ({ ...current, payment_date: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Reference"><input value={repay.reference} onChange={(event) => setRepay((current) => ({ ...current, reference: event.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><div className="flex justify-end gap-2 md:col-span-2 lg:col-span-3"><button type="button" onClick={closeMode} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button><button className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white">Review repayment</button></div></form> : null}
    </section> : null}
  </div>
  <FinancialConfirmationDialog open={confirmMode==="new"} title="Record this loan agreement?" description="This records the approved agreement only. It does not add cash and does not book outstanding principal until money is actually disbursed." details={approvalDetails} confirmLabel="Record agreement" loading={saving} warning="Approval is not disbursement. No bank/cash balance or loan principal payable will change at this step." onCancel={()=>setConfirmMode(null)} onConfirm={postApprove}/>
  <FinancialConfirmationDialog open={confirmMode==="receive"} title="Post loan disbursement?" description="This records money actually received from the lender and creates the corresponding loan principal liability." details={receiveDetails} confirmLabel="Post money received" loading={saving} warning="The principal disbursed increases loan principal due. Any withheld fee is posted separately and only the net amount reaches the selected account." onCancel={()=>setConfirmMode(null)} onConfirm={postReceive}/>
  <FinancialConfirmationDialog open={confirmMode==="repay"} title="Post loan repayment?" description="Check the principal, interest and fee split. The total will be deducted from the selected financial account." details={repayDetails} confirmLabel="Post repayment" loading={saving} warning="Principal reduces the loan liability; interest and fees are expenses. Verify the split before posting." onCancel={()=>setConfirmMode(null)} onConfirm={postRepay}/>
  </main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>; }
function Stat({ label, value, help }: { label: string; value: string; help: string }) { return <div className="rounded-xl bg-neutral-50 p-4"><p className="text-xs font-medium uppercase tracking-wide text-neutral-400">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-neutral-400">{help}</p></div>; }
function HistoryRow({title,date,meta,reference,notes}:{title:string;date:string;meta:string;reference:string|null;notes:string|null}) { return <div className="rounded-xl border p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-neutral-500">{meta}</p></div><p className="text-sm text-neutral-400">{date}</p></div>{reference?<p className="mt-2 text-xs text-neutral-400">Reference: {reference}</p>:null}{notes?<p className="mt-2 text-sm text-neutral-500">{notes}</p>:null}</div>; }
