"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowDownLeft, ArrowUpRight, Download, Landmark, Loader2, Search, X } from "lucide-react";
import { useParams } from "next/navigation";

import { AccountingNav } from "@/components/accounting-nav";
import { getApiErrorMessage } from "@/lib/api-error";

type Account = { id:string; name:string; account_type:string; provider_name:string|null; account_reference:string|null; currency:string; opening_balance:string|number; current_balance:string|number; is_active:boolean };
type Transaction = { id:string; transaction_date:string; direction:"credit"|"debit"|string; amount:string|number; currency:string; source_type:string; source_id:string; reference:string|null; description:string|null; created_at:string };
type LedgerRow = Transaction & { running_balance:number };

function money(value:string|number,currency:string){return `${currency} ${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function prettySource(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}
function csvCell(value:unknown){return `"${String(value??"").replaceAll('"','""')}"`}

export default function AccountLedgerPage(){
 const params=useParams<{accountId:string}>();const accountId=params.accountId;
 const[account,setAccount]=useState<Account|null>(null);const[transactions,setTransactions]=useState<Transaction[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const[search,setSearch]=useState("");const[direction,setDirection]=useState("all");const[source,setSource]=useState("all");const[fromDate,setFromDate]=useState("");const[toDate,setToDate]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[accountsRes,ledgerRes]=await Promise.all([fetch("/api/finance/accounts",{cache:"no-store"}),fetch(`/api/finance/accounts/${accountId}/ledger?limit=500`,{cache:"no-store"})]);const[accountsPayload,ledgerPayload]=await Promise.all([accountsRes.json(),ledgerRes.json()]);if(!accountsRes.ok)throw new Error(getApiErrorMessage(accountsPayload,"Could not load account"));if(!ledgerRes.ok)throw new Error(getApiErrorMessage(ledgerPayload,"Could not load account ledger"));const selected=(accountsPayload as Account[]).find(item=>item.id===accountId)??null;if(!selected)throw new Error("Financial account not found");setAccount(selected);setTransactions(ledgerPayload as Transaction[])}catch(reason){setError(reason instanceof Error?reason.message:"Could not load account ledger")}finally{setLoading(false)}},[accountId]);
 useEffect(()=>{void load()},[load]);
 const rows=useMemo<LedgerRow[]>(()=>{if(!account)return[];let running=Number(account.opening_balance||0);const ascending=[...transactions].sort((a,b)=>a.transaction_date.localeCompare(b.transaction_date)||a.created_at.localeCompare(b.created_at));return ascending.map(item=>{running+=item.direction==="credit"?Number(item.amount):-Number(item.amount);return{...item,running_balance:running}}).reverse()},[account,transactions]);
 const sources=useMemo(()=>[...new Set(transactions.map(item=>item.source_type))].sort(),[transactions]);
 const filteredRows=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(item=>{if(direction!=="all"&&item.direction!==direction)return false;if(source!=="all"&&item.source_type!==source)return false;if(fromDate&&item.transaction_date<fromDate)return false;if(toDate&&item.transaction_date>toDate)return false;if(q&&!`${item.description??""} ${item.reference??""} ${item.source_type} ${item.source_id}`.toLowerCase().includes(q))return false;return true})},[rows,search,direction,source,fromDate,toDate]);
 const totals=useMemo(()=>{let credit=0,debit=0;for(const item of transactions){if(item.direction==="credit")credit+=Number(item.amount);else debit+=Number(item.amount)}return{credit,debit}},[transactions]);
 const filteredTotals=useMemo(()=>{let credit=0,debit=0;for(const item of filteredRows){if(item.direction==="credit")credit+=Number(item.amount);else debit+=Number(item.amount)}return{credit,debit}},[filteredRows]);
 const hasFilters=Boolean(search||direction!=="all"||source!=="all"||fromDate||toDate);
 function clearFilters(){setSearch("");setDirection("all");setSource("all");setFromDate("");setToDate("")}
 function exportCsv(){if(!account)return;const header=["Date","Description","Source","Source ID","Reference","Debit","Credit","Running Balance"];const lines=[header.map(csvCell).join(","),...filteredRows.map(item=>[item.transaction_date,item.description||prettySource(item.source_type),prettySource(item.source_type),item.source_id,item.reference||"",item.direction==="debit"?Number(item.amount).toFixed(2):"",item.direction==="credit"?Number(item.amount).toFixed(2):"",item.running_balance.toFixed(2)].map(csvCell).join(","))];const blob=new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${account.name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-statement.csv`;link.click();URL.revokeObjectURL(url)}
 if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-7 animate-spin text-neutral-400"/></main>;
 return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div><Link href="/dashboard/accounting/accounts" className="inline-flex items-center gap-2 text-sm font-medium text-neutral-500 hover:text-neutral-950"><ArrowLeft className="size-4"/>Back to accounts</Link><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts · Account Ledger</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{account?.name??"Account ledger"}</h1><p className="mt-2 text-sm text-neutral-500">{account?.provider_name||account?.account_reference||"Full transaction history for this account."}</p></div>{account?<div className="rounded-2xl border bg-white px-5 py-4 text-right"><p className="text-xs text-neutral-400">Current balance</p><p className="mt-1 text-2xl font-semibold tabular-nums">{money(account.current_balance,account.currency)}</p></div>:null}</div></div>
  <AccountingNav/>{error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  {account?<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Opening balance" value={money(account.opening_balance,account.currency)}/><Stat label="Total credit" value={money(totals.credit,account.currency)} help="Money added to this account" icon={<ArrowDownLeft className="size-4 text-neutral-400"/>}/><Stat label="Total debit" value={money(totals.debit,account.currency)} help="Money deducted from this account" icon={<ArrowUpRight className="size-4 text-neutral-400"/>}/><Stat label="Current balance" value={money(account.current_balance,account.currency)} icon={<Landmark className="size-4 text-neutral-400"/>}/></section>:null}
  <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Account statement</h2><p className="mt-1 text-sm text-neutral-500">Search and filter without changing the running-balance calculation.</p></div><button onClick={exportCsv} disabled={!filteredRows.length} className="inline-flex items-center justify-center gap-2 rounded-xl border px-3 py-2 text-sm font-medium disabled:opacity-40"><Download className="size-4"/>Export CSV</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 size-4 text-neutral-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search description, reference or source..." className="h-10 w-full rounded-xl border pl-9 pr-3 text-sm"/></label><select value={direction} onChange={e=>setDirection(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="all">All movement</option><option value="credit">Money in / Credit</option><option value="debit">Money out / Debit</option></select><select value={source} onChange={e=>setSource(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="all">All sources</option>{sources.map(item=><option key={item} value={item}>{prettySource(item)}</option>)}</select><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="h-10 rounded-xl border px-3 text-sm" aria-label="From date"/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="h-10 rounded-xl border px-3 text-sm" aria-label="To date"/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-neutral-500"><span>Showing {filteredRows.length} of {rows.length} · Credit {account?money(filteredTotals.credit,account.currency):"—"} · Debit {account?money(filteredTotals.debit,account.currency):"—"}</span>{hasFilters?<button onClick={clearFilters} className="inline-flex items-center gap-1 font-medium text-neutral-700"><X className="size-3.5"/>Clear filters</button>:null}</div></div>
   <div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-4 py-3">Date</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th><th className="px-4 py-3 text-right">Balance</th></tr></thead><tbody>{filteredRows.map(item=><tr key={item.id} className="border-b last:border-0 hover:bg-neutral-50"><td className="px-4 py-3 whitespace-nowrap">{item.transaction_date}</td><td className="px-4 py-3"><p className="font-medium">{item.description||prettySource(item.source_type)}</p><p className="mt-1 font-mono text-[11px] text-neutral-400">{item.source_id}</p></td><td className="px-4 py-3"><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs text-neutral-600">{prettySource(item.source_type)}</span></td><td className="px-4 py-3">{item.reference||"—"}</td><td className="px-4 py-3 text-right font-medium tabular-nums">{item.direction==="debit"?money(item.amount,item.currency):"—"}</td><td className="px-4 py-3 text-right font-medium tabular-nums">{item.direction==="credit"?money(item.amount,item.currency):"—"}</td><td className="px-4 py-3 text-right font-semibold tabular-nums">{money(item.running_balance,item.currency)}</td></tr>)}</tbody></table>{!filteredRows.length&&!error?<div className="py-14 text-center"><p className="font-medium">{hasFilters?"No transactions match these filters":"No account transactions yet"}</p><p className="mt-1 text-sm text-neutral-400">{hasFilters?"Clear or change the filters to see more activity.":"Opening balance is shown above. New receipts, payments and transfers will appear here automatically."}</p></div>:null}</div>
  </section>
 </div></main>
}
function Stat({label,value,help,icon}:{label:string;value:string;help?:string;icon?:React.ReactNode}){return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm text-neutral-500">{label}</p>{icon}</div><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p>{help?<p className="mt-1 text-xs text-neutral-400">{help}</p>:null}</div>}
