"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, Plus } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Kind = "income" | "expense";
type FinancialAccount = { id: string; name: string; account_type: string; currency: string; current_balance: string; is_active: boolean };
type LedgerAccount = { id: string; code: string; name: string; category: string; is_active: boolean };
type MoneyEntry = { id: string; kind: Kind; entry_date: string; financial_account_id: string; financial_account_name: string; category_ledger_account_id: string; category_ledger_account_name: string; currency: string; amount: string; description: string; reference: string | null; created_at: string };
function today() { return new Date().toISOString().slice(0, 10); }
function money(value: string | number, currency: string) { return `${currency} ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export function AccountingMoneyPage({ kind }: { kind: Kind }) {
  const isIncome = kind === "income";
  const [accounts, setAccounts] = useState<FinancialAccount[]>([]); const [categories, setCategories] = useState<LedgerAccount[]>([]); const [entries, setEntries] = useState<MoneyEntry[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ entry_date: today(), financial_account_id: "", category_ledger_account_id: "", amount: "", description: "", reference: "", notes: "" });
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [a, c, e] = await Promise.all([fetch("/api/finance/accounts", { cache: "no-store" }), fetch("/api/accounting/chart-of-accounts", { cache: "no-store" }), fetch(`/api/accounting/money?kind=${kind}`, { cache: "no-store" })]); const ap = await a.json(); const cp = await c.json(); const ep = await e.json(); if (!a.ok) throw new Error(ap.detail ?? "Could not load financial accounts"); if (!c.ok) throw new Error(cp.detail ?? "Could not load accounting categories"); if (!e.ok) throw new Error(ep.detail ?? "Could not load transactions"); setAccounts(ap); setCategories(cp.filter((item: LedgerAccount) => item.category === kind && item.is_active)); setEntries(ep); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load money records"); } finally { setLoading(false); } }, [kind]);
  useEffect(() => { void load(); }, [load]);
  const selectedAccount = useMemo(() => accounts.find((a) => a.id === form.financial_account_id), [accounts, form.financial_account_id]);
  const usableAccounts = useMemo(() => accounts.filter((a) => a.is_active && (isIncome ? a.account_type !== "credit_card" : true)), [accounts, isIncome]);

  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch("/api/accounting/money", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, entry_date: form.entry_date, financial_account_id: form.financial_account_id, category_ledger_account_id: form.category_ledger_account_id, amount: Number(form.amount), description: form.description, reference: form.reference || null, notes: form.notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? `Could not record ${kind}`); setForm({ entry_date: today(), financial_account_id: "", category_ledger_account_id: "", amount: "", description: "", reference: "", notes: "" }); setShowForm(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : `Could not record ${kind}`); } finally { setSaving(false); } }

  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{isIncome ? "Money in" : "Money out"}</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">{isIncome ? "Record money your business received without thinking about debit or credit." : "Record money your business paid. Expenses charged to a credit card are treated as card liability automatically."}</p></div><button type="button" onClick={() => setShowForm((v) => !v)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white"><Plus className="size-4" />{isIncome ? "Record money received" : "Record payment"}</button></div>
    <AccountingNav />
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}

    {showForm ? <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-neutral-100">{isIncome ? <ArrowDownLeft className="size-5" /> : <ArrowUpRight className="size-5" />}</div><div><h2 className="font-semibold">{isIncome ? "What money did you receive?" : "What did you pay for?"}</h2><p className="mt-1 text-sm text-neutral-500">Fill in the real-world details. Business OS posts the accounting entry automatically.</p></div></div><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label={isIncome ? "Money received into" : "Paid from / charged to"}><select required value={form.financial_account_id} onChange={(e) => setForm((v) => ({ ...v, financial_account_id: e.target.value }))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select account</option>{usableAccounts.map((a) => <option key={a.id} value={a.id}>{a.name} — {money(a.current_balance, a.currency)}</option>)}</select></Field><Field label={isIncome ? "Income category" : "Expense category"}><select required value={form.category_ledger_account_id} onChange={(e) => setForm((v) => ({ ...v, category_ledger_account_id: e.target.value }))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Amount"><div className="flex rounded-xl border"><span className="border-r px-3 py-2.5 text-sm text-neutral-400">{selectedAccount?.currency ?? "—"}</span><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm((v) => ({ ...v, amount: e.target.value }))} className="min-w-0 flex-1 rounded-r-xl px-3 py-2.5 outline-none" /></div></Field><Field label="Date"><input required type="date" value={form.entry_date} onChange={(e) => setForm((v) => ({ ...v, entry_date: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Description"><input required value={form.description} onChange={(e) => setForm((v) => ({ ...v, description: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" placeholder={isIncome ? "Consulting income" : "Office internet bill"} /></Field><Field label="Reference (optional)"><input value={form.reference} onChange={(e) => setForm((v) => ({ ...v, reference: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><div className="md:col-span-2 lg:col-span-3 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving ? "Saving…" : isIncome ? "Confirm money received" : "Confirm payment"}</button></div></form></section> : null}

    <section className="rounded-2xl border bg-white p-5"><div><h2 className="font-semibold">Recent {isIncome ? "money received" : "payments"}</h2><p className="mt-1 text-sm text-neutral-500">Simple transactions recorded directly from this accounting workspace.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Date</th><th className="px-2 py-3">Description</th><th className="px-2 py-3">Category</th><th className="px-2 py-3">Account</th><th className="px-2 py-3 text-right">Amount</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-b last:border-0"><td className="px-2 py-3 text-neutral-500">{entry.entry_date}</td><td className="px-2 py-3"><p className="font-medium">{entry.description}</p><p className="text-xs text-neutral-400">{entry.reference || "No reference"}</p></td><td className="px-2 py-3">{entry.category_ledger_account_name}</td><td className="px-2 py-3">{entry.financial_account_name}</td><td className="px-2 py-3 text-right font-medium tabular-nums">{money(entry.amount, entry.currency)}</td></tr>)}</tbody></table>{!loading && entries.length === 0 ? <div className="py-12 text-center"><p className="font-medium">No records yet</p><p className="mt-1 text-sm text-neutral-400">Use the button above when the first transaction happens.</p></div> : null}</div></section>
  </div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>; }
