"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Building2, FolderKanban, HandCoins, ReceiptText, Users } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Purpose = "company" | "project" | "client";
type Account={id:string;name:string;currency:string;current_balance:string|number;is_active:boolean};
type Category={id:string;name:string;cost_type:string;is_active:boolean};
type Vendor={id:string;name:string;is_active:boolean};
type Client={id:string;code:string;name:string;currency:string|null};
type Project={id:string;number:string;name:string;client_id:string;client_name:string;currency:string;status:string};
type Meta={accounts:Account[];categories:Category[];vendors:Vendor[];clients:Client[];projects:Project[]};
type Expense={id:string;expense_number:string;description:string;expense_date:string;category_name:string;account_name:string;client_name:string|null;project_name:string|null;expense_currency:string;expense_amount:string|number;status:string};
function today(){return new Date().toISOString().slice(0,10)}
function money(value:string|number,currency:string){return `${currency} ${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}

const purposes=[
 {value:"company" as Purpose,title:"Company expense",help:"Office, software, rent, utilities and general business costs",icon:Building2},
 {value:"project" as Purpose,title:"Project expense",help:"Cost directly related to a project",icon:FolderKanban},
 {value:"client" as Purpose,title:"Client-related expense",help:"Cost incurred for a client outside a specific project",icon:Users},
];

export function MoneyOutWorkspace(){
 const[purpose,setPurpose]=useState<Purpose>("company");const[meta,setMeta]=useState<Meta>({accounts:[],categories:[],vendors:[],clients:[],projects:[]});const[expenses,setExpenses]=useState<Expense[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
 const[form,setForm]=useState({project_id:"",client_id:"",category_id:"",vendor_id:"",account_id:"",expense_amount:"",account_amount:"",expense_date:today(),description:"",payment_method:"bank_transfer",reference:"",tax_amount:"0",notes:""});
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[m,e]=await Promise.all([fetch("/api/finance/expense-meta",{cache:"no-store"}),fetch("/api/finance/expenses?status=posted&limit=50",{cache:"no-store"})]);const mp=await m.json();const ep=await e.json();if(!m.ok)throw new Error(mp.detail??"Could not load expense setup");if(!e.ok)throw new Error(ep.detail??"Could not load expenses");setMeta(mp);setExpenses(ep.items??[])}catch(reason){setError(reason instanceof Error?reason.message:"Could not load money-out workspace")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const account=meta.accounts.find(a=>a.id===form.account_id)??null;const project=meta.projects.find(p=>p.id===form.project_id)??null;const client=meta.clients.find(c=>c.id===(purpose==="project"?project?.client_id:form.client_id))??null;
 const expenseCurrency=purpose==="project"?(project?.currency??account?.currency??""):purpose==="client"?(client?.currency??account?.currency??""):(account?.currency??"");
 const crossCurrency=Boolean(account&&expenseCurrency&&account.currency!==expenseCurrency);
 const projects=meta.projects.filter(p=>p.status!=="cancelled");
 function changePurpose(next:Purpose){setPurpose(next);setForm(v=>({...v,project_id:"",client_id:"",account_amount:""}));setMessage(null);setError(null)}
 async function submit(event:FormEvent){event.preventDefault();if(!account)return;setSaving(true);setError(null);setMessage(null);try{const body={description:form.description,category_id:form.category_id,account_id:account.id,vendor_id:form.vendor_id||null,client_id:purpose==="client"?form.client_id:null,project_id:purpose==="project"?form.project_id:null,expense_date:form.expense_date,expense_currency:expenseCurrency,expense_amount:Number(form.expense_amount),account_amount:crossCurrency?Number(form.account_amount):null,tax_amount:Number(form.tax_amount||0),payment_method:form.payment_method,reference:form.reference||null,notes:form.notes||null};const response=await fetch("/api/finance/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not record expense");setMessage(`Expense ${payload.expense_number} recorded. Account balance, project/client profitability and accounting records were updated.`);setForm({project_id:"",client_id:"",category_id:"",vendor_id:"",account_id:"",expense_amount:"",account_amount:"",expense_date:today(),description:"",payment_method:"bank_transfer",reference:"",tax_amount:"0",notes:""});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not record expense")}finally{setSaving(false)}}
 return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Money out</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Tell Business OS what the payment was for. Project, client and company expense tracking happens automatically.</p></div><AccountingNav/>
  {error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>:null}
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">What was this payment for?</h2><p className="mt-1 text-sm text-neutral-500">Choose the business purpose first. Only relevant fields will be shown.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{purposes.map(({value,title,help,icon:Icon})=><button key={value} type="button" onClick={()=>changePurpose(value)} className={`rounded-2xl border p-4 text-left ${purpose===value?"border-neutral-950 bg-neutral-950 text-white":"hover:bg-neutral-50"}`}><Icon className="size-5"/><p className="mt-3 font-semibold">{title}</p><p className={`mt-1 text-xs ${purpose===value?"text-neutral-300":"text-neutral-500"}`}>{help}</p></button>)}<Link href="/dashboard/accounting/payables" className="rounded-2xl border p-4 hover:bg-neutral-50"><ReceiptText className="size-5"/><p className="mt-3 font-semibold">Supplier bill payment</p><p className="mt-1 text-xs text-neutral-500">Pay an existing vendor bill without creating a second expense.</p></Link><Link href="/dashboard/accounting/loans" className="rounded-2xl border p-4 hover:bg-neutral-50"><HandCoins className="size-5"/><p className="mt-3 font-semibold">Loan repayment</p><p className="mt-1 text-xs text-neutral-500">Split principal, interest and fees correctly.</p></Link></div>
   <form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
    {purpose==="project"?<Field label="Project"><select required value={form.project_id} onChange={e=>setForm(v=>({...v,project_id:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.number} · {p.name} · {p.client_name}</option>)}</select>{project?<Hint>Client: {project.client_name} · Project currency: {project.currency}</Hint>:null}</Field>:null}
    {purpose==="client"?<Field label="Client"><select required value={form.client_id} onChange={e=>setForm(v=>({...v,client_id:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select client</option>{meta.clients.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field>:null}
    <Field label="Expense category"><select required value={form.category_id} onChange={e=>setForm(v=>({...v,category_id:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select category</option>{meta.categories.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
    <Field label="Paid from / charged to"><select required value={form.account_id} onChange={e=>setForm(v=>({...v,account_id:e.target.value,account_amount:""}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select account</option>{meta.accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.current_balance,a.currency)}</option>)}</select></Field>
    <Field label="Expense amount"><div className="flex rounded-xl border"><span className="border-r px-3 py-2.5 text-sm text-neutral-400">{expenseCurrency||"—"}</span><input required type="number" min="0.01" step="0.01" value={form.expense_amount} onChange={e=>setForm(v=>({...v,expense_amount:e.target.value}))} className="min-w-0 flex-1 rounded-r-xl px-3 py-2.5 outline-none"/></div></Field>
    {crossCurrency?<Field label={`Actual deducted from ${account?.name}`}><div className="flex rounded-xl border"><span className="border-r px-3 py-2.5 text-sm text-neutral-400">{account?.currency}</span><input required type="number" min="0.01" step="0.01" value={form.account_amount} onChange={e=>setForm(v=>({...v,account_amount:e.target.value}))} className="min-w-0 flex-1 rounded-r-xl px-3 py-2.5 outline-none"/></div><Hint>Use the exact amount shown by the bank/wallet. Business OS calculates the effective exchange rate.</Hint></Field>:null}
    <Field label="Description"><input required value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} placeholder={purpose==="project"?"Hosting, design asset, contractor…":"What did the business pay for?"} className="w-full rounded-xl border px-3 py-2.5"/></Field>
    <Field label="Vendor / supplier (optional)"><select value={form.vendor_id} onChange={e=>setForm(v=>({...v,vendor_id:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">No vendor</option>{meta.vendors.filter(v=>v.is_active).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><Hint>Use Payables instead if this is payment against a previously recorded vendor bill.</Hint></Field>
    <Field label="Date"><input required type="date" value={form.expense_date} onChange={e=>setForm(v=>({...v,expense_date:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field>
    <Field label="Payment method"><select value={form.payment_method} onChange={e=>setForm(v=>({...v,payment_method:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="payoneer">Payoneer</option><option value="wise">Wise</option><option value="stripe">Stripe</option><option value="paypal">PayPal</option><option value="fiverr">Fiverr</option><option value="other">Other</option></select></Field>
    <Field label="Tax included (optional)"><input type="number" min="0" step="0.01" value={form.tax_amount} onChange={e=>setForm(v=>({...v,tax_amount:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><Field label="Reference (optional)"><input value={form.reference} onChange={e=>setForm(v=>({...v,reference:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field>
    <div className="md:col-span-2 lg:col-span-3 flex justify-end"><button disabled={saving||loading} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-5 py-2.5 text-sm font-medium text-white disabled:opacity-50"><ArrowUpRight className="size-4"/>{saving?"Saving…":"Confirm payment"}</button></div>
   </form>
  </section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Recent expenses</h2><p className="mt-1 text-sm text-neutral-500">Company, project and client-related expenses share one source of truth.</p><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Date</th><th className="px-2 py-3">Expense</th><th className="px-2 py-3">Purpose</th><th className="px-2 py-3">Category</th><th className="px-2 py-3">Account</th><th className="px-2 py-3 text-right">Amount</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id} className="border-b last:border-0"><td className="px-2 py-3 text-neutral-500">{e.expense_date}</td><td className="px-2 py-3"><p className="font-medium">{e.description}</p><p className="text-xs text-neutral-400">{e.expense_number}</p></td><td className="px-2 py-3">{e.project_name?`Project · ${e.project_name}`:e.client_name?`Client · ${e.client_name}`:"Company"}</td><td className="px-2 py-3">{e.category_name}</td><td className="px-2 py-3">{e.account_name}</td><td className="px-2 py-3 text-right font-medium">{money(e.expense_amount,e.expense_currency)}</td></tr>)}</tbody></table>{!loading&&!expenses.length?<p className="py-10 text-center text-sm text-neutral-400">No expenses recorded yet.</p>:null}</div></section>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>}
function Hint({children}:{children:React.ReactNode}){return <span className="mt-1 block text-xs font-normal text-neutral-400">{children}</span>}
