"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { BarChart3, FileClock, Landmark, RefreshCw, Scale, TrendingUp } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Row={code:string;name:string;amount:string|number};
type Statements={base_currency:string;date_from:string;date_to:string;income:Row[];expenses:Row[];total_income:string|number;total_expenses:string|number;net_profit:string|number;assets:Row[];liabilities:Row[];equity:Row[];total_assets:string|number;total_liabilities:string|number;recorded_equity:string|number;current_earnings:string|number;total_equity:string|number;total_liabilities_and_equity:string|number;cash_flow:{operating:string|number;investing:string|number;financing:string|number;net_change:string|number}};
function money(v:string|number,currency:string){return `${currency} ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}

export default function AccountingReportsPage(){
 const[data,setData]=useState<Statements|null>(null);const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[error,setError]=useState<string|null>(null);const[warning,setWarning]=useState<string|null>(null);const[dateFrom,setDateFrom]=useState("");const[dateTo,setDateTo]=useState("");
 const load=useCallback(async(sync=false)=>{setLoading(true);setError(null);setWarning(null);try{if(sync){setSyncing(true);const sr=await fetch("/api/accounting/sync",{method:"POST"});const sp=await sr.json().catch(()=>null);if(sr.ok&&sp?.errors?.length)setWarning(`${sp.errors.length} record(s) could not be synchronized yet. Most commonly a required FX rate is missing.`);else if(!sr.ok&&sr.status!==403)setWarning(sp?.detail??"Some older transactions could not be synchronized automatically.")}const params=new URLSearchParams();if(dateFrom)params.set("date_from",dateFrom);if(dateTo)params.set("date_to",dateTo);const response=await fetch(`/api/accounting/reports/financial-statements${params.size?`?${params}`:""}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not load financial statements");setData(payload)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load financial reports")}finally{setLoading(false);setSyncing(false)}},[dateFrom,dateTo]);
 useEffect(()=>{void load(true)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const c=data?.base_currency??"";return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Financial reports</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Business-friendly Profit & Loss, Balance Sheet and Cash Flow generated from posted accounting records.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/accounting/reports/account-statement" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-medium"><FileClock className="size-4"/>Account statement</Link><button onClick={()=>void load(true)} disabled={syncing} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-medium disabled:opacity-50"><RefreshCw className={`size-4 ${syncing?"animate-spin":""}`}/>Refresh accounting</button></div></div><AccountingNav/>
  {error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}{warning?<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">{warning}</div>:null}
  <section className="rounded-2xl border bg-white p-4"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm"><span className="mb-1.5 block text-neutral-500">From</span><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm"><span className="mb-1.5 block text-neutral-500">To</span><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label><div className="flex items-end"><button onClick={()=>void load(false)} className="w-full rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white">Apply period</button></div></div>{data?<p className="mt-3 text-xs text-neutral-400">Showing {data.date_from} to {data.date_to} · Base currency {data.base_currency}</p>:null}</section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={TrendingUp} label="Income" value={data?money(data.total_income,c):"—"}/><Metric icon={BarChart3} label="Expenses" value={data?money(data.total_expenses,c):"—"}/><Metric icon={Scale} label="Net profit" value={data?money(data.net_profit,c):"—"}/><Metric icon={Landmark} label="Net cash movement" value={data?money(data.cash_flow.net_change,c):"—"}/></section>
  <section className="grid gap-4 lg:grid-cols-2"><Statement title="Profit & Loss" subtitle="Income minus expenses for the selected period." sections={[{label:"Income",rows:data?.income??[]},{label:"Expenses",rows:data?.expenses??[]}]} footer={[["Total income",data?.total_income??0],["Total expenses",data?.total_expenses??0],["Net profit",data?.net_profit??0]]} currency={c}/><Statement title="Balance Sheet" subtitle="What the business owns, owes and has accumulated." sections={[{label:"Assets",rows:data?.assets??[]},{label:"Liabilities",rows:data?.liabilities??[]},{label:"Equity",rows:data?.equity??[]}]} footer={[["Total assets",data?.total_assets??0],["Total liabilities",data?.total_liabilities??0],["Current earnings",data?.current_earnings??0],["Total equity",data?.total_equity??0],["Liabilities + equity",data?.total_liabilities_and_equity??0]]} currency={c}/></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Cash Flow</h2><p className="mt-1 text-sm text-neutral-500">How cash moved during the selected period.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Small label="Operating" value={data?money(data.cash_flow.operating,c):"—"}/><Small label="Investing" value={data?money(data.cash_flow.investing,c):"—"}/><Small label="Financing" value={data?money(data.cash_flow.financing,c):"—"}/><Small label="Net change" value={data?money(data.cash_flow.net_change,c):"—"}/></div></section>{loading?<p className="text-center text-sm text-neutral-400">Refreshing financial reports…</p>:null}
 </div></main>}
function Metric({icon:Icon,label,value}:{icon:typeof BarChart3;label:string;value:string}){return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm text-neutral-500">{label}</p><Icon className="size-5 text-neutral-400"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-neutral-50 p-4"><p className="text-xs uppercase tracking-wide text-neutral-400">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function Statement({title,subtitle,sections,footer,currency}:{title:string;subtitle:string;sections:Array<{label:string;rows:Row[]}>;footer:Array<[string,string|number]>;currency:string}){return <div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-neutral-500">{subtitle}</p><div className="mt-5 space-y-5">{sections.map(section=><div key={section.label}><p className="text-xs font-semibold uppercase tracking-wide text-neutral-400">{section.label}</p><div className="mt-2 divide-y">{section.rows.length?section.rows.map(row=><div key={row.code} className="flex items-center justify-between gap-4 py-2 text-sm"><span>{row.name}</span><span className="font-medium tabular-nums">{money(row.amount,currency)}</span></div>):<p className="py-2 text-sm text-neutral-400">No activity</p>}</div></div>)}</div><div className="mt-5 border-t pt-3">{footer.map(([label,value])=><div key={label} className="flex items-center justify-between py-1.5 text-sm"><span className="text-neutral-500">{label}</span><span className="font-semibold tabular-nums">{money(value,currency)}</span></div>)}</div></div>}
