"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, FileText, Loader2, LogIn, LogOut, Megaphone, ReceiptText, Star, UserRound } from "lucide-react";
import { SearchableSelect } from "@/components/searchable-select";

type SelfData = {
  employee: { id:string; employee_code:string; employment_status:string; join_date?:string; work_location?:string };
  leave_requests: { id:string; leave_type?:string; start_date:string; end_date:string; days:string; status:string }[];
  attendance: { date:string; status:string; check_in_at?:string; check_out_at?:string; work_minutes:number }[];
  documents: { id:string; title:string; document_type:string; expires_on?:string; file_url?:string }[];
  performance: { id:string; period_start:string; period_end:string; status:string; rating?:string; self_review?:string; manager_review?:string }[];
  announcements: { id:string; title:string; body:string; is_policy:boolean; published_at?:string }[];
  payslips: { run_id:string; entry_id:string; run_number:string; period_name:string; currency:string; gross_pay:string; net_pay:string; status:string }[];
};
type Meta = { leave_types: { id:string; name:string; annual_allowance_days:string; is_paid:boolean }[] };
type PolicyAck = Record<string,string>;

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||"Request failed");return b as T;}

export default function MyHRPage(){
  const[data,setData]=useState<SelfData|null>(null),[meta,setMeta]=useState<Meta|null>(null),[acks,setAcks]=useState<PolicyAck>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
  useEffect(()=>{void load();},[]);
  async function load(){setLoading(true);setError(null);try{const[s,m,a]=await Promise.all([api<SelfData>("/api/hr/self"),api<Meta>("/api/hr/self-meta"),api<PolicyAck>("/api/hr/self/policy-acknowledgements")]);setData(s);setMeta(m);setAcks(a);}catch(e){setError(e instanceof Error?e.message:"Unable to load My HR");}finally{setLoading(false)}}
  async function action(path:string,message:string){setBusy(true);setError(null);setSuccess(null);try{await api(`/api/hr/${path}`,{method:"POST"});setSuccess(message);setData(await api<SelfData>("/api/hr/self"));}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false)}}
  async function acknowledge(id:string){setBusy(true);setError(null);try{const result=await api<{announcement_id:string;acknowledged_at:string}>(`/api/hr/self/announcements/${id}/acknowledge`,{method:"POST"});setAcks(old=>({...old,[id]:result.acknowledged_at}));setSuccess("Policy acknowledged.");}catch(e){setError(e instanceof Error?e.message:"Unable to acknowledge policy");}finally{setBusy(false)}}
  async function requestLeave(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setError(null);setSuccess(null);try{await api("/api/hr/leave-requests",{method:"POST",body:JSON.stringify({leave_type_id:d.get("leave_type_id"),start_date:d.get("start_date"),end_date:d.get("end_date"),reason:d.get("reason")||null})});form.reset();setSuccess("Leave request submitted.");setData(await api<SelfData>("/api/hr/self"));}catch(e){setError(e instanceof Error?e.message:"Unable to request leave");}finally{setBusy(false)}}
  async function saveSelfReview(id:string,text:string){setBusy(true);setError(null);try{await api(`/api/hr/self/performance/${id}`,{method:"PATCH",body:JSON.stringify({self_review:text})});setSuccess("Self review saved.");setData(await api<SelfData>("/api/hr/self"));}catch(e){setError(e instanceof Error?e.message:"Unable to save self review");}finally{setBusy(false)}}
  const leaveOptions=useMemo(()=>(meta?.leave_types??[]).map(x=>({value:x.id,label:`${x.name} · ${x.annual_allowance_days} days${x.is_paid?" · paid":""}`})),[meta]);
  const recent=data?.attendance?.[0];
  if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-7 animate-spin text-neutral-400"/></main>;
  return <main className="min-h-screen bg-neutral-100 p-4 sm:p-8 lg:p-10"><div className="mx-auto max-w-[1400px]">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-neutral-500">Your workday and employee records</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">My HR</h1><p className="mt-2 text-sm text-neutral-500">Check in, request leave, read policies and find your documents, reviews and payslips in one place.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void action("self/check-in","Checked in successfully.")} className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm disabled:opacity-40"><LogIn className="size-4"/>Check in</button><button disabled={busy} onClick={()=>void action("self/check-out","Checked out successfully.")} className="inline-flex h-10 items-center gap-2 rounded-xl bg-neutral-950 px-4 text-sm text-white disabled:opacity-40"><LogOut className="size-4"/>Check out</button></div></header>
    {error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}{success?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</div>:null}
    {data?<><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Card icon={UserRound} label="Employee" value={data.employee.employee_code}/><Card icon={CalendarDays} label="Status" value={data.employee.employment_status}/><Card icon={Clock3} label="Recent attendance" value={recent?.status||"No record"}/><Card icon={FileText} label="Documents" value={String(data.documents.length)}/><Card icon={ReceiptText} label="Payslips" value={String(data.payslips.length)}/></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><form onSubmit={requestLeave} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Request leave</h2><p className="mt-1 text-xs text-neutral-500">Choose your dates and the company leave policy. No HR terminology required.</p><div className="mt-4 space-y-4"><SearchableSelect label="Leave type" name="leave_type_id" required options={leaveOptions}/><Field name="start_date" label="Start date" type="date"/><Field name="end_date" label="End date" type="date"/><label className="block text-sm font-medium">Reason<textarea name="reason" className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><button disabled={busy} className="h-11 w-full rounded-xl bg-neutral-950 text-sm font-semibold text-white disabled:opacity-50">Submit request</button></div></form><Section title="Leave history"><SimpleTable headers={["Type","Dates","Days","Status"]} rows={data.leave_requests.map(x=>[x.leave_type||"—",`${x.start_date} — ${x.end_date}`,x.days,x.status])}/></Section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Section title="Recent attendance"><SimpleTable headers={["Date","Status","Work"]} rows={data.attendance.slice(0,20).map(x=>[x.date,x.status,`${x.work_minutes}m`])}/></Section><Section title="My documents"><div className="space-y-3">{data.documents.length?data.documents.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{x.title}</p><p className="text-xs text-neutral-500">{x.document_type} · Expiry {x.expires_on||"N/A"}</p></div>{x.file_url?<a href={`/api/hr-documents/self/${x.id}/file`} target="_blank" rel="noreferrer" className="text-sm font-medium underline">Open</a>:null}</div>):<Empty/>}</div></Section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Section title="Performance"><div className="space-y-3">{data.performance.length?data.performance.map(x=><PerformanceItem key={x.id} row={x} busy={busy} onSave={saveSelfReview}/>):<Empty/>}</div></Section><Section title="Payslips"><div className="space-y-3">{data.payslips.length?data.payslips.map(x=><Link key={x.entry_id} href={`/dashboard/payroll/${x.run_id}/payslip/${x.entry_id}`} className="flex items-center justify-between rounded-xl border p-4 hover:bg-neutral-50"><div><p className="font-medium">{x.period_name}</p><p className="text-xs text-neutral-500">{x.run_number} · {x.status}</p></div><div className="text-right"><p className="font-semibold">{x.currency} {Number(x.net_pay).toLocaleString()}</p><p className="text-xs text-neutral-400">View payslip</p></div></Link>):<Empty/>}</div></Section></div>
    <Section title="Policies & announcements" extraClass="mt-5"><div className="grid gap-3 md:grid-cols-2">{data.announcements.length?data.announcements.map(x=><div key={x.id} className="rounded-xl border p-4"><div className="flex items-center gap-2"><Megaphone className="size-4"/><p className="font-medium">{x.title}</p>{x.is_policy?<span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] text-amber-700">POLICY</span>:null}</div><p className="mt-2 whitespace-pre-wrap text-sm text-neutral-600">{x.body}</p>{x.is_policy?<div className="mt-4">{acks[x.id]?<div className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700"><CheckCircle2 className="size-4"/>Acknowledged</div>:<button disabled={busy} onClick={()=>void acknowledge(x.id)} className="rounded-lg bg-neutral-950 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50">Acknowledge policy</button>}</div>:null}</div>):<Empty/>}</div></Section></>:null}
  </div></main>;
}
function PerformanceItem({row,busy,onSave}:{row:SelfData["performance"][number];busy:boolean;onSave:(id:string,text:string)=>Promise<void>}){const[text,setText]=useState(row.self_review||"");return <div className="rounded-xl border p-4"><div className="flex items-center justify-between"><div><p className="font-medium">{row.period_start} — {row.period_end}</p><p className="text-xs capitalize text-neutral-500">{row.status}</p></div><div className="flex items-center gap-1 font-semibold"><Star className="size-4"/>{row.rating||"—"}</div></div>{row.status!=="completed"?<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write your self review…" className="mt-3 min-h-20 w-full rounded-lg border p-2 text-sm"/><button disabled={busy||!text.trim()} onClick={()=>void onSave(row.id,text)} className="mt-2 rounded-lg border px-3 py-1.5 text-xs font-medium disabled:opacity-40">Save self review</button></>:row.self_review?<p className="mt-3 text-sm text-neutral-600">{row.self_review}</p>:null}{row.manager_review?<div className="mt-3 rounded-lg bg-neutral-50 p-3 text-sm text-neutral-600"><strong>Manager:</strong> {row.manager_review}</div>:null}</div>}
function Card({icon:Icon,label,value}:{icon:typeof UserRound;label:string;value:string}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-xs text-neutral-500"><Icon className="size-4"/>{label}</div><p className="mt-2 text-lg font-semibold capitalize">{value.replaceAll("_"," ")}</p></div>}
function Field({name,label,type}:{name:string;label:string;type:string}){return <label className="block text-sm font-medium">{label}<input name={name} type={type} required className="mt-2 h-11 w-full rounded-xl border px-3"/></label>}
function Section({title,children,extraClass=""}:{title:string;children:React.ReactNode;extraClass?:string}){return <section className={`${extraClass} rounded-2xl border bg-white p-5 shadow-sm`}><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
function SimpleTable({headers,rows}:{headers:string[];rows:string[][]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase tracking-wide text-neutral-400"><tr>{headers.map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className="px-4 py-3 capitalize">{c.replaceAll("_"," ")}</td>)}</tr>)}</tbody></table></div>}
function Empty(){return <div className="rounded-xl border border-dashed py-10 text-center text-sm text-neutral-400">No records yet.</div>}
