"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Calculator, Loader2, RefreshCw, TrendingUp } from "lucide-react";

type Pnl={currency:string;investment_income:string;loan_interest:string;investor_profit_share:string;net_capital_pnl_impact:string};
type Investor={investor_id:string;investor_name:string;share_type:string;share_value:string;invested_amount:string;principal_returned:string;principal_remaining:string;profit_entitlement:string;profit_paid:string;profit_remaining:string;status:string};
type Settlement={project_id:string;project_number:string;project_name:string;currency:string;status:string;revenue:string;direct_cost:string;project_profit:string;total_investor_profit_entitlement:string;total_investor_profit_paid:string;company_retained_profit:string;investors:Investor[]};
type Data={date_from:string;date_to:string;overdue_loans:number;capital_pnl:Pnl[];project_settlements:Settlement[]};
const money=(v:string|number,c:string)=>`${c} ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function CapitalInsightsPage(){
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const r=await fetch("/api/capital/insights",{cache:"no-store"});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||"Unable to load capital insights");setData(b)}catch(e){setError(e instanceof Error?e.message:"Unable to load capital insights")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 if(loading&&!data)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-7 animate-spin text-neutral-400"/></main>;
 return <main className="min-h-screen bg-neutral-100 p-4 sm:p-7 lg:p-10"><div className="mx-auto max-w-[1500px]">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-neutral-500">Capital analytics</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Funding Insights & Settlement</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Capital P&L impact is kept separate from principal movements. Project settlement uses invoiced revenue minus posted direct project cost.</p></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm"><RefreshCw className="size-4"/>Refresh</button></header>
  {error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Stat icon={AlertTriangle} label="Overdue loans" value={String(data?.overdue_loans??0)} danger={(data?.overdue_loans??0)>0}/><Stat icon={TrendingUp} label="Capital currencies" value={String(data?.capital_pnl.length??0)}/><Stat icon={Calculator} label="Investor projects" value={String(data?.project_settlements.length??0)}/></div>
  <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div><p className="text-sm text-neutral-500">Current year / selected API period</p><h2 className="mt-1 text-xl font-semibold">Capital P&L Impact</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-neutral-400"><Th>Currency</Th><Th>Investment income</Th><Th>Loan interest</Th><Th>Investor profit share</Th><Th>Net capital impact</Th></tr></thead><tbody>{data?.capital_pnl.length?data.capital_pnl.map(x=><tr key={x.currency} className="border-b last:border-0"><Td strong>{x.currency}</Td><Td>{money(x.investment_income,x.currency)}</Td><Td>{money(x.loan_interest,x.currency)}</Td><Td>{money(x.investor_profit_share,x.currency)}</Td><Td strong>{money(x.net_capital_pnl_impact,x.currency)}</Td></tr>):<tr><td colSpan={5} className="py-10 text-center text-neutral-400">No capital P&L activity in this period.</td></tr>}</tbody></table></div></section>
  <div className="mt-5 space-y-5">{data?.project_settlements.length?data.project_settlements.map(p=><section key={p.project_id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm text-neutral-500">{p.project_number} · {p.status}</p><h2 className="mt-1 text-xl font-semibold">{p.project_name}</h2></div><div className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm lg:text-right"><span className="text-neutral-400">Project profit</span><strong>{money(p.project_profit,p.currency)}</strong><span className="text-neutral-400">Investor entitlement</span><strong>{money(p.total_investor_profit_entitlement,p.currency)}</strong><span className="text-neutral-400">Company retained</span><strong>{money(p.company_retained_profit,p.currency)}</strong></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Invoiced revenue" value={money(p.revenue,p.currency)}/><Mini label="Direct cost" value={money(p.direct_cost,p.currency)}/><Mini label="Investor profit paid" value={money(p.total_investor_profit_paid,p.currency)}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-neutral-400"><Th>Investor</Th><Th>Agreement</Th><Th>Invested</Th><Th>Principal remaining</Th><Th>Profit entitlement</Th><Th>Profit paid</Th><Th>Profit remaining</Th></tr></thead><tbody>{p.investors.map(i=><tr key={i.investor_id} className="border-b last:border-0"><Td strong>{i.investor_name}</Td><Td>{i.share_type==="profit_percent"?`${Number(i.share_value)}%`:`Fixed ${money(i.share_value,p.currency)}`}</Td><Td>{money(i.invested_amount,p.currency)}</Td><Td>{money(i.principal_remaining,p.currency)}</Td><Td>{money(i.profit_entitlement,p.currency)}</Td><Td>{money(i.profit_paid,p.currency)}</Td><Td strong>{money(i.profit_remaining,p.currency)}</Td></tr>)}</tbody></table></div></section>):<section className="rounded-2xl border border-dashed bg-white p-10 text-center text-sm text-neutral-400">No project investors yet.</section>}</div>
 </div></main>
}
function Stat({icon:Icon,label,value,danger=false}:{icon:typeof AlertTriangle;label:string;value:string;danger?:boolean}){return <div className={`rounded-2xl border bg-white p-5 shadow-sm ${danger?"border-red-200":""}`}><Icon className={`size-5 ${danger?"text-red-500":"text-neutral-400"}`}/><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-neutral-500">{label}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-neutral-50 p-3"><p className="text-xs text-neutral-400">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
function Th({children}:{children:React.ReactNode}){return <th className="px-3 py-3 font-medium">{children}</th>}
function Td({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <td className={`px-3 py-3 ${strong?"font-semibold":""}`}>{children}</td>}
