"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, Clock3, Loader2, Plus, RefreshCw, SlidersHorizontal } from "lucide-react";
import { SearchableSelect } from "@/components/searchable-select";

type Meta = { employees:{id:string;employee_code:string;name:string}[]; leave_types:{id:string;name:string;code:string;annual_allowance_days:string;is_paid:boolean}[]; shifts:{id:string;name:string;start_time:string;end_time:string}[] };
type Holiday={id:string;name:string;holiday_date:string;is_paid:boolean;notes?:string};
type Assignment={id:string;employee_id:string;employee_code:string;employee_name:string;shift_id:string;shift_name:string;effective_from:string;effective_to?:string};

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail||"Request failed");return b as T;}

export default function HRSetupPage(){
  const[meta,setMeta]=useState<Meta|null>(null),[holidays,setHolidays]=useState<Holiday[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
  useEffect(()=>{void load();},[]);
  async function load(){setLoading(true);setError(null);try{const[m,h,a]=await Promise.all([api<Meta>("/api/hr/meta"),api<Holiday[]>("/api/hr/holidays"),api<Assignment[]>("/api/hr/shift-assignments")]);setMeta(m);setHolidays(h);setAssignments(a);}catch(e){setError(e instanceof Error?e.message:"Unable to load HR setup");}finally{setLoading(false)}}
  async function post(path:string,payload:Record<string,unknown>,message:string,form:HTMLFormElement){setBusy(true);setError(null);setSuccess(null);try{await api(`/api/hr/${path}`,{method:"POST",body:JSON.stringify(payload)});form.reset();setSuccess(message);await load();}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false)}}
  const employeeOptions=useMemo(()=>(meta?.employees??[]).map(x=>({value:x.id,label:`${x.employee_code} · ${x.name}`})),[meta]);
  const shiftOptions=useMemo(()=>(meta?.shifts??[]).map(x=>({value:x.id,label:`${x.name} · ${x.start_time.slice(0,5)}–${x.end_time.slice(0,5)}`})),[meta]);
  if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-7 animate-spin text-neutral-400"/></main>;
  return <main className="min-h-screen bg-neutral-100 p-4 sm:p-8 lg:p-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-neutral-500">HR configuration</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">HR Setup</h1><p className="mt-2 text-sm text-neutral-500">Leave policies, work shifts, employee shift assignments and company holidays.</p></div><button onClick={()=>void load()} disabled={busy} className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm"><RefreshCw className="size-4"/>Refresh</button></header>
    {error?<Notice kind="error" text={error}/>:null}{success?<Notice kind="success" text={success}/>:null}
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <Card icon={CalendarDays} title="Leave types"><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void post("leave-types",{name:d.get("name"),code:d.get("code"),annual_allowance_days:Number(d.get("days")||0),is_paid:d.get("is_paid")==="on",requires_approval:true},"Leave type created.",f)}} className="grid gap-3 sm:grid-cols-2"><Field name="name" label="Name" required/><Field name="code" label="Code" required/><Field name="days" label="Annual days" type="number" defaultValue="0"/><label className="flex items-center gap-2 self-end pb-3 text-sm"><input name="is_paid" type="checkbox" defaultChecked/>Paid leave</label><Submit busy={busy} text="Add leave type"/></form><div className="mt-5 space-y-2">{(meta?.leave_types??[]).map(x=><Row key={x.id} title={`${x.name} (${x.code})`} detail={`${x.annual_allowance_days} days · ${x.is_paid?"Paid":"Unpaid"}`}/>)}</div></Card>
      <Card icon={Clock3} title="Work shifts"><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void post("shifts",{name:d.get("name"),start_time:d.get("start_time"),end_time:d.get("end_time"),break_minutes:Number(d.get("break_minutes")||0),grace_minutes:Number(d.get("grace_minutes")||0),weekly_off_days:[]},"Shift created.",f)}} className="grid gap-3 sm:grid-cols-2"><Field name="name" label="Shift name" required/><Field name="start_time" label="Start" type="time" required/><Field name="end_time" label="End" type="time" required/><Field name="break_minutes" label="Break minutes" type="number" defaultValue="60"/><Field name="grace_minutes" label="Grace minutes" type="number" defaultValue="10"/><Submit busy={busy} text="Add shift"/></form><div className="mt-5 space-y-2">{(meta?.shifts??[]).map(x=><Row key={x.id} title={x.name} detail={`${x.start_time.slice(0,5)} — ${x.end_time.slice(0,5)}`}/>)}</div></Card>
      <Card icon={SlidersHorizontal} title="Shift assignment"><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void post("shift-assignments",{employee_id:d.get("employee_id"),shift_id:d.get("shift_id"),effective_from:d.get("effective_from")},"Shift assigned.",f)}} className="space-y-3"><SearchableSelect label="Employee" name="employee_id" required options={employeeOptions}/><SearchableSelect label="Shift" name="shift_id" required options={shiftOptions}/><Field name="effective_from" label="Effective from" type="date" required/><Submit busy={busy} text="Assign shift"/></form><div className="mt-5 space-y-2">{assignments.length?assignments.map(x=><Row key={x.id} title={`${x.employee_code} · ${x.employee_name}`} detail={`${x.shift_name} · from ${x.effective_from}`}/>):<Empty/>}</div></Card>
      <Card icon={CalendarDays} title="Holiday calendar"><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void post("holidays",{name:d.get("name"),holiday_date:d.get("holiday_date"),is_paid:d.get("is_paid")==="on",notes:d.get("notes")||null},"Holiday added.",f)}} className="grid gap-3 sm:grid-cols-2"><Field name="name" label="Holiday name" required/><Field name="holiday_date" label="Date" type="date" required/><label className="flex items-center gap-2 text-sm"><input name="is_paid" type="checkbox" defaultChecked/>Paid holiday</label><Field name="notes" label="Notes"/><Submit busy={busy} text="Add holiday"/></form><div className="mt-5 space-y-2">{holidays.length?holidays.map(x=><Row key={x.id} title={x.name} detail={`${x.holiday_date} · ${x.is_paid?"Paid":"Unpaid"}`}/>):<Empty/>}</div></Card>
    </div>
  </div></main>;
}
function Card({icon:Icon,title,children}:{icon:typeof CalendarDays;title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Icon className="size-4"/><h2 className="font-semibold">{title}</h2></div><div className="mt-4">{children}</div></section>}
function Field({name,label,type="text",required=false,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string}){return <label className="block text-sm font-medium">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>}
function Submit({busy,text}:{busy:boolean;text:string}){return <button disabled={busy} className="sm:col-span-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-neutral-950 text-sm font-semibold text-white disabled:opacity-50"><Plus className="size-4"/>{text}</button>}
function Row({title,detail}:{title:string;detail:string}){return <div className="rounded-xl border px-4 py-3"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-neutral-500">{detail}</p></div>}
function Empty(){return <div className="rounded-xl border border-dashed py-8 text-center text-sm text-neutral-400">No records yet.</div>}
function Notice({kind,text}:{kind:"error"|"success";text:string}){return <div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${kind==="error"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{text}</div>}
