"use client";
import { FormEvent, useEffect, useState } from "react";
import { Loader2, Save, Settings2 } from "lucide-react";
type Defaults={default_client_country_code:string|null;default_client_currency:string|null;default_document_language:string;default_lead_status:string;default_project_status:string;default_order_status:string;default_invoice_status:string;quotation_validity_days:number};
export default function SettingsPage(){const [form,setForm]=useState<Defaults|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{void fetch('/api/settings/system-defaults',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail??'Unable to load settings');setForm(d);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function save(e:FormEvent){e.preventDefault();if(!form)return;setSaving(true);setError(null);setMessage(null);try{const r=await fetch('/api/settings/system-defaults',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.detail??'Unable to save settings');setForm(d);setMessage('Business defaults saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save settings');}finally{setSaving(false);}}
 if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-6 animate-spin"/></main>; if(!form)return <main className="p-8 text-sm text-red-700">{error??'Settings unavailable'}</main>;
 const field=(key:keyof Defaults,label:string,help:string)=><label className="block"><span className="text-sm font-semibold">{label}</span><input value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:key==='quotation_validity_days'?Number(e.target.value):e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-neutral-500"/><span className="mt-1 block text-xs text-neutral-400">{help}</span></label>;
 return <main className="min-h-screen bg-neutral-100 p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl"><p className="text-sm text-neutral-500">Company-wide behaviour</p><h1 className="mt-1 text-3xl font-semibold">Settings</h1><form onSubmit={save} className="mt-7 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Settings2 className="size-5"/><div><h2 className="font-semibold">System defaults</h2><p className="text-sm text-neutral-500">New records inherit these values; existing historical documents are not rewritten.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-2">{field('default_client_country_code','Default client country','ISO country code, for example BD, US or AU.')}{field('default_client_currency','Default client currency','ISO currency code, for example USD, BDT or AUD.')}{field('default_document_language','Document language','Default language code for generated business documents.')}{field('quotation_validity_days','Quotation validity days','Default validity period for new quotations.')}{field('default_lead_status','Default lead status','Initial CRM lead status.')}{field('default_project_status','Default project status','Initial project status when applicable.')}{field('default_order_status','Default order status','Initial order status when applicable.')}{field('default_invoice_status','Default invoice status','Initial invoice status when applicable.')}</div>{error?<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{message?<p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>:null}<div className="mt-6 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Save settings</button></div></form></div></main>}
