"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, Loader2, Plus, RefreshCw, Save } from "lucide-react";

import { SearchableSelect, type SearchOption } from "@/components/searchable-select";
import { COUNTRY_OPTIONS, CURRENCY_OPTIONS, LANGUAGE_OPTIONS } from "@/lib/company-options";

type Defaults = { default_client_country_code:string|null; default_client_currency:string|null; default_document_language:string; default_lead_status:string; default_project_status:string; default_order_status:string; default_invoice_status:string; quotation_validity_days:number };
type RatePolicy = { mode:"automatic"|"manual"|"automatic_adjusted"; provider:string; adjustment_percent:string; sync_frequency:"manual"|"daily"; last_synced_at:string|null };
type Rate = { id:string; base_currency:string; quote_currency:string; reference_rate:string|null; manual_rate:string|null; effective_rate:string; source:string; synced_at:string|null };
type RateBundle = { policy:RatePolicy; rates:Rate[] };
type CrmMeta = { statuses:{name:string;slug:string;is_active:boolean}[] };

const PROJECT_STATUS_OPTIONS:SearchOption[]=[{value:"planned",label:"Planned"},{value:"active",label:"Active"}];
const ORDER_STATUS_OPTIONS:SearchOption[]=[{value:"draft",label:"Draft"},{value:"confirmed",label:"Confirmed"}];
const INVOICE_STATUS_OPTIONS:SearchOption[]=[{value:"draft",label:"Draft"},{value:"sent",label:"Sent"}];
const MODE_OPTIONS:SearchOption[]=[{value:"automatic",label:"Automatic — live reference rate"},{value:"manual",label:"Manual — admin controlled"},{value:"automatic_adjusted",label:"Automatic + adjustment"}];

export default function SettingsPage(){
 const [form,setForm]=useState<Defaults|null>(null); const [leadStatuses,setLeadStatuses]=useState<SearchOption[]>([]); const [rates,setRates]=useState<RateBundle|null>(null);
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [syncing,setSyncing]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 const [base,setBase]=useState("USD"); const [quote,setQuote]=useState("BDT"); const [manualRate,setManualRate]=useState("");
 useEffect(()=>{void(async()=>{try{const [s,c,r]=await Promise.all([fetch("/api/settings/system-defaults",{cache:"no-store"}),fetch("/api/crm/meta",{cache:"no-store"}),fetch("/api/settings/exchange-rates",{cache:"no-store"})]); const sp=await s.json().catch(()=>null); if(!s.ok)throw new Error(sp?.detail??"Unable to load settings"); setForm(sp); if(c.ok){const cp=await c.json() as CrmMeta;setLeadStatuses(cp.statuses.filter(x=>x.is_active).map(x=>({value:x.slug,label:x.name})))} if(r.ok)setRates(await r.json());}catch(e){setError(e instanceof Error?e.message:"Unable to load settings")}finally{setLoading(false)}})()},[]);
 const currencyOptions=useMemo(()=>CURRENCY_OPTIONS,[]);
 async function saveDefaults(e:FormEvent){e.preventDefault();if(!form)return;setSaving(true);setError(null);setMessage(null);try{const r=await fetch("/api/settings/system-defaults",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail??"Unable to save settings");setForm(p);setMessage("Business defaults saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}finally{setSaving(false)}}
 async function savePolicy(){if(!rates)return;setSaving(true);setError(null);try{const r=await fetch("/api/settings/exchange-rates/policy",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(rates.policy)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail??"Unable to save exchange-rate policy");setRates({...rates,policy:p});setMessage("Exchange-rate policy saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save exchange-rate policy")}finally{setSaving(false)}}
 async function addPair(){setError(null);try{const r=await fetch("/api/settings/exchange-rates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({base_currency:base,quote_currency:quote,manual_rate:rates?.policy.mode==="manual"?Number(manualRate):null})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail??"Unable to add currency pair");if(rates)setRates({...rates,rates:[...rates.rates,p]});setManualRate("")}catch(e){setError(e instanceof Error?e.message:"Unable to add currency pair")}}
 async function sync(){setSyncing(true);setError(null);try{const r=await fetch("/api/settings/exchange-rates/sync",{method:"POST"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail??"Unable to sync rates");setRates(p);setMessage("Live exchange rates synced.")}catch(e){setError(e instanceof Error?e.message:"Unable to sync rates")}finally{setSyncing(false)}}
 if(loading)return <main className="flex min-h-[70vh] items-center justify-center"><Loader2 className="size-6 animate-spin"/></main>; if(!form)return <main className="p-8 text-sm text-red-700">{error??"Settings unavailable"}</main>;
 const leadOptions=leadStatuses.length?leadStatuses:[{value:form.default_lead_status,label:form.default_lead_status}];
 return <main className="min-h-screen bg-neutral-100 p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl"><p className="text-sm text-neutral-500">Company-wide behaviour</p><h1 className="mt-1 text-3xl font-semibold">Settings</h1>
  <form onSubmit={saveDefaults} className="mt-7 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">System defaults</h2><p className="mt-1 text-sm text-neutral-500">New records inherit these values; historical documents are never rewritten.</p><div className="mt-6 grid gap-5 md:grid-cols-2">
   <SearchableSelect label="Default client country" name="country" value={form.default_client_country_code} onValueChange={v=>setForm({...form,default_client_country_code:v})} options={COUNTRY_OPTIONS} placeholder="Select country" searchPlaceholder="Search country..."/>
   <SearchableSelect label="Default client currency" name="currency" value={form.default_client_currency} onValueChange={v=>setForm({...form,default_client_currency:v})} options={CURRENCY_OPTIONS} placeholder="Select currency" searchPlaceholder="Search currency..."/>
   <SearchableSelect label="Document language" name="language" value={form.default_document_language} onValueChange={v=>setForm({...form,default_document_language:v})} options={LANGUAGE_OPTIONS} placeholder="Select language" searchPlaceholder="Search language..."/>
   <label className="block"><span className="text-sm font-semibold">Quotation validity days</span><input type="number" min={1} max={365} value={form.quotation_validity_days} onChange={e=>setForm({...form,quotation_validity_days:Number(e.target.value)})} className="mt-2 h-11 w-full rounded-xl border px-3 text-sm"/></label>
   <SearchableSelect label="Default lead status" name="lead" value={form.default_lead_status} onValueChange={v=>setForm({...form,default_lead_status:v})} options={leadOptions} placeholder="Select status"/>
   <SearchableSelect label="Default project status" name="project" value={form.default_project_status} onValueChange={v=>setForm({...form,default_project_status:v})} options={PROJECT_STATUS_OPTIONS} placeholder="Select status"/>
   <SearchableSelect label="Default order status" name="order" value={form.default_order_status} onValueChange={v=>setForm({...form,default_order_status:v})} options={ORDER_STATUS_OPTIONS} placeholder="Select status"/>
   <SearchableSelect label="Default invoice status" name="invoice" value={form.default_invoice_status} onValueChange={v=>setForm({...form,default_invoice_status:v})} options={INVOICE_STATUS_OPTIONS} placeholder="Select status"/>
  </div><div className="mt-6 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><Save className="size-4"/>Save defaults</button></div></form>

  {rates?<section className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><ArrowRightLeft className="size-5"/><h2 className="font-semibold">Exchange rates</h2></div><p className="mt-1 text-sm text-neutral-500">Global FX policy for estimated current values. Historical transaction rates remain locked.</p></div>{rates.policy.mode!=="manual"?<button onClick={()=>void sync()} disabled={syncing} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><RefreshCw className={`size-4 ${syncing?"animate-spin":""}`}/>Sync now</button>:null}</div>
   <div className="mt-6 grid gap-5 md:grid-cols-2"><SearchableSelect label="Rate mode" name="fx_mode" value={rates.policy.mode} onValueChange={v=>setRates({...rates,policy:{...rates.policy,mode:v as RatePolicy["mode"]}})} options={MODE_OPTIONS} placeholder="Select mode"/><SearchableSelect label="Provider" name="provider" value={rates.policy.provider} onValueChange={v=>setRates({...rates,policy:{...rates.policy,provider:v}})} options={[{value:"frankfurter",label:"Frankfurter — reference rates"}]} placeholder="Select provider"/>
    {rates.policy.mode==="automatic_adjusted"?<label><span className="text-sm font-semibold">Operational adjustment %</span><input type="number" step="0.01" min={-50} max={50} value={rates.policy.adjustment_percent} onChange={e=>setRates({...rates,policy:{...rates.policy,adjustment_percent:e.target.value}})} className="mt-2 h-11 w-full rounded-xl border px-3 text-sm"/><span className="mt-1 block text-xs text-neutral-400">Example: -1.00% models a provider/bank rate below the reference rate.</span></label>:null}
    <SearchableSelect label="Sync frequency" name="sync_frequency" value={rates.policy.sync_frequency} onValueChange={v=>setRates({...rates,policy:{...rates.policy,sync_frequency:v as RatePolicy["sync_frequency"]}})} options={[{value:"daily",label:"Daily"},{value:"manual",label:"Only when Sync now is pressed"}]} placeholder="Select frequency"/>
   </div><div className="mt-5 flex justify-end"><button type="button" onClick={()=>void savePolicy()} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white">Save FX policy</button></div>
   <div className="mt-6 border-t pt-6"><h3 className="font-semibold">Currency pairs</h3><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_1fr_1fr_auto]"><SearchableSelect label="From" name="fx_base" value={base} onValueChange={setBase} options={currencyOptions} placeholder="Base"/><div className="hidden pt-9 text-neutral-300 sm:block">→</div><SearchableSelect label="To" name="fx_quote" value={quote} onValueChange={setQuote} options={currencyOptions} placeholder="Quote"/>{rates.policy.mode==="manual"?<label><span className="text-sm font-semibold">Manual rate</span><input value={manualRate} onChange={e=>setManualRate(e.target.value)} type="number" step="0.000001" className="mt-2 h-11 w-full rounded-xl border px-3 text-sm"/></label>:<div/>}<button type="button" onClick={()=>void addPair()} className="mt-7 inline-flex h-11 items-center justify-center gap-2 rounded-xl border px-4 text-sm font-semibold"><Plus className="size-4"/>Add</button></div>
    <div className="mt-5 overflow-hidden rounded-xl border"><div className="grid grid-cols-[1fr_1fr_1fr_auto] bg-neutral-50 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-neutral-400"><span>Pair</span><span>Reference</span><span>Effective</span><span>Source</span></div>{rates.rates.length?rates.rates.map(r=><div key={r.id} className="grid grid-cols-[1fr_1fr_1fr_auto] items-center border-t px-4 py-3 text-sm"><span className="font-semibold">{r.base_currency} → {r.quote_currency}</span><span>{r.reference_rate??"—"}</span><span className="font-semibold">{r.effective_rate}</span><span className="text-xs capitalize text-neutral-400">{r.source}</span></div>):<p className="p-5 text-sm text-neutral-400">No currency pairs configured yet.</p>}</div>
    <p className="mt-3 text-xs text-neutral-400">Last live sync: {rates.policy.last_synced_at?new Date(rates.policy.last_synced_at).toLocaleString():"Never"}. Live/operational rates are estimates only; actual payment and transfer rates remain immutable.</p>
   </div>
  </section>:null}
  {error?<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{message?<p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>:null}
 </div></main>
}
