"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CircleDollarSign, Receipt } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Invoice = { id: string; invoice_number: string; client_name: string; status: string; display_status: string; issue_date: string; due_date: string | null; currency: string; total: string; amount_paid: string; balance_due: string };
type Account = { id: string; name: string; currency: string; current_balance: string; account_type: string; is_active: boolean };
function money(value: string | number, currency: string) { return `${currency} ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function today() { return new Date().toISOString().slice(0, 10); }

export default function ReceivablesPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState<Invoice | null>(null);
  const [form, setForm] = useState({ account_id: "", payment_date: today(), invoice_amount: "", method: "bank_transfer", reference: "", notes: "" });
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [i, a] = await Promise.all([fetch("/api/finance/invoices?limit=200", { cache: "no-store" }), fetch("/api/finance/accounts", { cache: "no-store" })]); const ip = await i.json(); const ap = await a.json(); if (!i.ok) throw new Error(ip.detail ?? "Could not load invoices"); if (!a.ok) throw new Error(ap.detail ?? "Could not load accounts"); setInvoices((ip.items ?? ip).filter((item: Invoice) => Number(item.balance_due) > 0 && item.status !== "cancelled")); setAccounts(ap); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load receivables"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const totals = useMemo(() => { const result = new Map<string, number>(); for (const invoice of invoices) result.set(invoice.currency, (result.get(invoice.currency) ?? 0) + Number(invoice.balance_due)); return [...result.entries()]; }, [invoices]);
  const compatibleAccounts = useMemo(() => selected ? accounts.filter((a) => a.is_active && a.currency === selected.currency && a.account_type !== "credit_card") : [], [accounts, selected]);

  function openPayment(invoice: Invoice) { setSelected(invoice); setForm({ account_id: "", payment_date: today(), invoice_amount: invoice.balance_due, method: "bank_transfer", reference: "", notes: "" }); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(null); try { const response = await fetch("/api/finance/payments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invoice_id: selected.id, account_id: form.account_id, payment_date: form.payment_date, invoice_amount: Number(form.invoice_amount), method: form.method, reference: form.reference || null, notes: form.notes || null }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? "Could not record customer payment"); setSelected(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not record payment"); } finally { setSaving(false); } }

  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Customer receivables</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">Invoices customers still owe you. Record payment only when the money actually reaches one of your accounts.</p></div>
    <AccountingNav />
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-neutral-500">Open invoices</p><p className="mt-2 text-3xl font-semibold">{invoices.length}</p></div><div className="rounded-2xl border bg-white p-5 sm:col-span-1 lg:col-span-3"><p className="text-sm text-neutral-500">Total customers owe you</p><div className="mt-2 flex flex-wrap gap-x-8 gap-y-1">{totals.length ? totals.map(([currency, value]) => <p key={currency} className="text-2xl font-semibold">{money(value, currency)}</p>) : <p className="text-2xl font-semibold">0.00</p>}</div></div></section>

    <section className="rounded-2xl border bg-white p-5"><div><h2 className="font-semibold">Who still owes you?</h2><p className="mt-1 text-sm text-neutral-500">Outstanding and partially paid invoices.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Invoice</th><th className="px-2 py-3">Customer</th><th className="px-2 py-3">Due date</th><th className="px-2 py-3">Total</th><th className="px-2 py-3">Paid</th><th className="px-2 py-3">Still due</th><th className="px-2 py-3"></th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-b last:border-0"><td className="px-2 py-3 font-medium">{invoice.invoice_number}</td><td className="px-2 py-3">{invoice.client_name}</td><td className="px-2 py-3 text-neutral-500">{invoice.due_date || "—"}</td><td className="px-2 py-3 tabular-nums">{money(invoice.total, invoice.currency)}</td><td className="px-2 py-3 tabular-nums text-neutral-500">{money(invoice.amount_paid, invoice.currency)}</td><td className="px-2 py-3 font-semibold tabular-nums">{money(invoice.balance_due, invoice.currency)}</td><td className="px-2 py-3 text-right"><button onClick={() => openPayment(invoice)} className="rounded-lg bg-neutral-950 px-3 py-2 text-xs font-medium text-white">Record payment</button></td></tr>)}</tbody></table>{!loading && invoices.length === 0 ? <div className="py-12 text-center"><Receipt className="mx-auto size-8 text-neutral-300" /><p className="mt-3 font-medium">Nothing outstanding</p><p className="mt-1 text-sm text-neutral-400">All current invoices are paid or there are no invoices yet.</p></div> : null}</div></section>

    {selected ? <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-neutral-100"><CircleDollarSign className="size-5" /></div><div><h2 className="font-semibold">Record payment for {selected.invoice_number}</h2><p className="mt-1 text-sm text-neutral-500">{selected.client_name} currently owes {money(selected.balance_due, selected.currency)}.</p></div></div><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Money received into"><select required value={form.account_id} onChange={(e) => setForm((v) => ({ ...v, account_id: e.target.value }))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select account</option>{compatibleAccounts.map((a) => <option key={a.id} value={a.id}>{a.name} — {money(a.current_balance, a.currency)}</option>)}</select></Field><Field label="Amount received"><input required type="number" min="0.01" max={selected.balance_due} step="0.01" value={form.invoice_amount} onChange={(e) => setForm((v) => ({ ...v, invoice_amount: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Payment date"><input required type="date" value={form.payment_date} onChange={(e) => setForm((v) => ({ ...v, payment_date: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><Field label="Payment method"><select value={form.method} onChange={(e) => setForm((v) => ({ ...v, method: e.target.value }))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="payoneer">Payoneer</option><option value="wise">Wise</option><option value="stripe">Stripe</option><option value="paypal">PayPal</option><option value="other">Other</option></select></Field><Field label="Reference"><input value={form.reference} onChange={(e) => setForm((v) => ({ ...v, reference: e.target.value }))} className="w-full rounded-xl border px-3 py-2.5" /></Field><div className="flex items-end justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white">{saving ? "Saving…" : "Confirm payment"}</button></div></form></section> : null}
  </div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>; }
