"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, Receipt, WalletCards } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Invoice={id:string;client_id:string;invoice_number:string;client_name:string;status:string;display_status:string;issue_date:string;due_date:string|null;currency:string;total:string|number;amount_paid:string|number;balance_due:string|number};
type Advance={id:string;client_id:string;client_name:string;advance_date:string;currency:string;original_amount:string|number;remaining_amount:string|number;reference:string|null};
function today(){return new Date().toISOString().slice(0,10)}function money(value:string|number,currency:string){return `${currency} ${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}

export default function ReceivablesPage(){
 const[invoices,setInvoices]=useState<Invoice[]>([]);const[advances,setAdvances]=useState<Advance[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[selected,setSelected]=useState<Invoice|null>(null);const[form,setForm]=useState({advance_id:"",amount:"",application_date:today()});
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[i,a]=await Promise.all([fetch("/api/finance/invoices?limit=200",{cache:"no-store"}),fetch("/api/accounting/customer-advances?open_only=true",{cache:"no-store"})]);const[ip,ap]=await Promise.all([i.json(),a.json()]);if(!i.ok)throw new Error(ip.detail??"Could not load receivables");if(!a.ok)throw new Error(ap.detail??"Could not load customer advances");setInvoices((ip.items??ip).filter((item:Invoice)=>Number(item.balance_due)>0&&!['draft','cancelled','paid'].includes(item.status)));setAdvances(ap)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load receivables")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const result=new Map<string,number>();for(const invoice of invoices)result.set(invoice.currency,(result.get(invoice.currency)??0)+Number(invoice.balance_due));return [...result.entries()]},[invoices]);
 const advanceTotals=useMemo(()=>{const result=new Map<string,number>();for(const advance of advances)result.set(advance.currency,(result.get(advance.currency)??0)+Number(advance.remaining_amount));return [...result.entries()]},[advances]);
 const matchingAdvances=selected?advances.filter(a=>a.client_id===selected.client_id&&a.currency===selected.currency&&Number(a.remaining_amount)>0):[];const selectedAdvance=matchingAdvances.find(a=>a.id===form.advance_id)??null;
 function openApply(invoice:Invoice){const options=advances.filter(a=>a.client_id===invoice.client_id&&a.currency===invoice.currency&&Number(a.remaining_amount)>0);setSelected(invoice);setForm({advance_id:options[0]?.id??"",amount:options[0]?String(Math.min(Number(options[0].remaining_amount),Number(invoice.balance_due))):"",application_date:today()});setMessage(null)}
 async function apply(event:FormEvent){event.preventDefault();if(!selected||!selectedAdvance)return;setSaving(true);setError(null);setMessage(null);try{const response=await fetch(`/api/accounting/customer-advances/${selectedAdvance.id}/apply`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoice_id:selected.id,application_date:form.application_date,amount:Number(form.amount)})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not apply customer advance");setMessage(`Customer credit applied to ${selected.invoice_number}. No bank or wallet balance changed because the money was already received earlier.`);setSelected(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not apply advance")}finally{setSaving(false)}}
 return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Receivables</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">See who owes you and use customer credit safely. New cash receipts are recorded only from Money In.</p></div><Link href="/dashboard/accounting/money-in" className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white"><ArrowDownLeft className="size-4"/>Collect money</Link></div><AccountingNav/>{error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>:null}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-neutral-500">Open invoices</p><p className="mt-2 text-3xl font-semibold">{invoices.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-neutral-500">Customers owe you</p><div className="mt-2 space-y-1">{totals.length?totals.map(([currency,value])=><p key={currency} className="text-xl font-semibold">{money(value,currency)}</p>):<p className="text-xl font-semibold">0.00</p>}</div></div><div className="rounded-2xl border bg-white p-5 sm:col-span-2"><p className="text-sm text-neutral-500">Unused customer credit</p><div className="mt-2 flex flex-wrap gap-x-8 gap-y-1">{advanceTotals.length?advanceTotals.map(([currency,value])=><p key={currency} className="text-xl font-semibold">{money(value,currency)}</p>):<p className="text-xl font-semibold">0.00</p>}</div><p className="mt-2 text-xs text-neutral-400">Already received money waiting to be applied to invoices.</p></div></section>
  {selected?<section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-neutral-100"><WalletCards className="size-5"/></div><div><h2 className="font-semibold">Apply customer credit to {selected.invoice_number}</h2><p className="mt-1 text-sm text-neutral-500">This settles receivable using money already received earlier. Cash will not move again.</p></div></div>{matchingAdvances.length?<form onSubmit={apply} className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Available advance"><select required value={form.advance_id} onChange={e=>{const advance=matchingAdvances.find(a=>a.id===e.target.value);setForm(v=>({...v,advance_id:e.target.value,amount:advance?String(Math.min(Number(advance.remaining_amount),Number(selected.balance_due))):""}))}} className="w-full rounded-xl border bg-white px-3 py-2.5">{matchingAdvances.map(a=><option key={a.id} value={a.id}>{a.advance_date} · {money(a.remaining_amount,a.currency)} remaining</option>)}</select></Field><Field label="Amount to apply"><input required type="number" min="0.01" max={Math.min(Number(selected.balance_due),Number(selectedAdvance?.remaining_amount??0))} step="0.01" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><Field label="Application date"><input required type="date" value={form.application_date} onChange={e=>setForm(v=>({...v,application_date:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><div className="flex items-end gap-2"><button type="button" onClick={()=>setSelected(null)} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button><button disabled={saving} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving?"Applying…":"Apply credit"}</button></div></form>:<div className="mt-4 rounded-xl bg-neutral-50 p-4 text-sm text-neutral-500">This customer has no matching unused advance in {selected.currency}. <Link href="/dashboard/accounting/money-in" className="font-medium text-neutral-950 underline">Record an advance in Money In</Link> if money was received before invoicing.</div>}</section>:null}
  <section className="rounded-2xl border bg-white p-5"><div><h2 className="font-semibold">Who still owes you?</h2><p className="mt-1 text-sm text-neutral-500">Collect new money in Money In, or apply existing customer credit here.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Invoice</th><th className="px-2 py-3">Customer</th><th className="px-2 py-3">Due date</th><th className="px-2 py-3">Total</th><th className="px-2 py-3">Paid / credit</th><th className="px-2 py-3">Still due</th><th className="px-2 py-3"></th></tr></thead><tbody>{invoices.map(invoice=>{const hasCredit=advances.some(a=>a.client_id===invoice.client_id&&a.currency===invoice.currency&&Number(a.remaining_amount)>0);return <tr key={invoice.id} className="border-b last:border-0"><td className="px-2 py-3 font-medium">{invoice.invoice_number}</td><td className="px-2 py-3">{invoice.client_name}</td><td className="px-2 py-3 text-neutral-500">{invoice.due_date||"—"}</td><td className="px-2 py-3">{money(invoice.total,invoice.currency)}</td><td className="px-2 py-3 text-neutral-500">{money(invoice.amount_paid,invoice.currency)}</td><td className="px-2 py-3 font-semibold">{money(invoice.balance_due,invoice.currency)}</td><td className="px-2 py-3"><div className="flex justify-end gap-2">{hasCredit?<button onClick={()=>openApply(invoice)} className="rounded-lg border px-3 py-2 text-xs font-medium">Apply credit</button>:null}<Link href="/dashboard/accounting/money-in" className="rounded-lg bg-neutral-950 px-3 py-2 text-xs font-medium text-white">Collect</Link></div></td></tr>})}</tbody></table>{!loading&&!invoices.length?<div className="py-12 text-center"><Receipt className="mx-auto size-8 text-neutral-300"/><p className="mt-3 font-medium">Nothing outstanding</p><p className="mt-1 text-sm text-neutral-400">All current invoices are paid or there are no invoices yet.</p></div>:null}</div></section>
 </div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>}
