"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, Receipt } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type Invoice = { id:string; invoice_number:string; client_name:string; status:string; display_status:string; issue_date:string; due_date:string|null; currency:string; total:string|number; amount_paid:string|number; balance_due:string|number };
function money(value:string|number,currency:string){return `${currency} ${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}

export default function ReceivablesPage(){
 const[invoices,setInvoices]=useState<Invoice[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch("/api/finance/invoices?limit=200",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not load receivables");setInvoices((payload.items??payload).filter((item:Invoice)=>Number(item.balance_due)>0&&!['draft','cancelled','paid'].includes(item.status)))}catch(reason){setError(reason instanceof Error?reason.message:"Could not load receivables")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const totals=useMemo(()=>{const result=new Map<string,number>();for(const invoice of invoices)result.set(invoice.currency,(result.get(invoice.currency)??0)+Number(invoice.balance_due));return [...result.entries()]},[invoices]);
 return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Receivables</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">See who still owes your business. Money is recorded only from Money In, so customer payments never get entered twice.</p></div><Link href="/dashboard/accounting/money-in" className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white"><ArrowDownLeft className="size-4"/>Collect money</Link></div>
  <AccountingNav/>{error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-neutral-500">Open invoices</p><p className="mt-2 text-3xl font-semibold">{invoices.length}</p></div><div className="rounded-2xl border bg-white p-5 sm:col-span-1 lg:col-span-3"><p className="text-sm text-neutral-500">Total customers owe you</p><div className="mt-2 flex flex-wrap gap-x-8 gap-y-1">{totals.length?totals.map(([currency,value])=><p key={currency} className="text-2xl font-semibold">{money(value,currency)}</p>):<p className="text-2xl font-semibold">0.00</p>}</div></div></section>
  <section className="rounded-2xl border bg-white p-5"><div><h2 className="font-semibold">Who still owes you?</h2><p className="mt-1 text-sm text-neutral-500">Outstanding and partially paid invoices. Use Money In when payment actually arrives.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Invoice</th><th className="px-2 py-3">Customer</th><th className="px-2 py-3">Due date</th><th className="px-2 py-3">Total</th><th className="px-2 py-3">Paid</th><th className="px-2 py-3">Still due</th><th className="px-2 py-3"></th></tr></thead><tbody>{invoices.map(invoice=><tr key={invoice.id} className="border-b last:border-0"><td className="px-2 py-3 font-medium">{invoice.invoice_number}</td><td className="px-2 py-3">{invoice.client_name}</td><td className="px-2 py-3 text-neutral-500">{invoice.due_date||"—"}</td><td className="px-2 py-3">{money(invoice.total,invoice.currency)}</td><td className="px-2 py-3 text-neutral-500">{money(invoice.amount_paid,invoice.currency)}</td><td className="px-2 py-3 font-semibold">{money(invoice.balance_due,invoice.currency)}</td><td className="px-2 py-3 text-right"><Link href="/dashboard/accounting/money-in" className="rounded-lg border px-3 py-2 text-xs font-medium hover:bg-neutral-50">Collect in Money In</Link></td></tr>)}</tbody></table>{!loading&&!invoices.length?<div className="py-12 text-center"><Receipt className="mx-auto size-8 text-neutral-300"/><p className="mt-3 font-medium">Nothing outstanding</p><p className="mt-1 text-sm text-neutral-400">All current invoices are paid or there are no invoices yet.</p></div>:null}</div></section>
 </div></main>
}
