"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BookOpen, Plus, RotateCcw } from "lucide-react";

import { AccountingNav } from "@/components/accounting-nav";

type LedgerAccount = { id:string; code:string; name:string; category:"asset"|"liability"|"equity"|"income"|"expense"; subtype:string|null; normal_balance:"debit"|"credit"; parent_id:string|null; system_key:string|null; is_system:boolean; is_active:boolean; allow_manual_posting:boolean; notes:string|null };
type TrialBalance = { total_debit:string; total_credit:string; rows:Array<{ ledger_account_id:string; code:string; name:string; category:LedgerAccount["category"]; debit:string; credit:string; balance:string }> };
type Journal={id:string;entry_number:string;entry_date:string;status:string;source_type:string;source_id:string|null;reference:string|null;memo:string|null;total_debit:string;total_credit:string;created_at:string;posted_at:string;lines:Array<{id:string;account_code:string;account_name:string;description:string|null;currency:string;debit:string;credit:string;original_amount:string}>};
const categories:LedgerAccount["category"][]=["asset","liability","equity","income","expense"];
function money(value:string|number){return Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}function pretty(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())}

export default function AdvancedAccountingPage(){
 const[accounts,setAccounts]=useState<LedgerAccount[]>([]);const[trial,setTrial]=useState<TrialBalance|null>(null);const[journals,setJournals]=useState<Journal[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[showForm,setShowForm]=useState(false);const[expanded,setExpanded]=useState<string|null>(null);
 const[form,setForm]=useState({code:"",name:"",category:"asset" as LedgerAccount["category"],subtype:"",normal_balance:"debit" as "debit"|"credit",parent_id:"",notes:""});
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[a,t,j]=await Promise.all([fetch("/api/accounting/chart-of-accounts",{cache:"no-store"}),fetch("/api/accounting/trial-balance",{cache:"no-store"}),fetch("/api/accounting/journals?limit=100",{cache:"no-store"})]);const[ap,tp,jp]=await Promise.all([a.json(),t.json(),j.json()]);if(!a.ok)throw new Error(ap.detail??"Could not load chart of accounts");if(!t.ok)throw new Error(tp.detail??"Could not load trial balance");if(!j.ok)throw new Error(jp.detail??"Could not load journals");setAccounts(ap);setTrial(tp);setJournals(jp)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load advanced accounting")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const balanced=useMemo(()=>Number(trial?.total_debit??0)===Number(trial?.total_credit??0),[trial]);
 function changeCategory(category:LedgerAccount["category"]){setForm(v=>({...v,category,normal_balance:category==="asset"||category==="expense"?"debit":"credit",parent_id:""}))}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError(null);try{const response=await fetch("/api/accounting/chart-of-accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,subtype:form.subtype||null,parent_id:form.parent_id||null,notes:form.notes||null})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not create ledger account");setForm({code:"",name:"",category:"asset",subtype:"",normal_balance:"debit",parent_id:"",notes:""});setShowForm(false);setMessage("Ledger account created.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not create ledger account")}finally{setSaving(false)}}
 async function reverse(entry:Journal){if(entry.source_type==="reversal")return;setSaving(true);setError(null);setMessage(null);try{const response=await fetch(`/api/accounting/journals/${entry.id}/reverse`,{method:"POST"});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Could not reverse journal");setMessage(`${entry.entry_number} reversed with ${payload.entry_number}.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not reverse journal")}finally{setSaving(false)}}
 return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">Finance & Accounts</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Advanced accounting</h1><p className="mt-2 max-w-3xl text-sm text-neutral-500">For accountants and advanced users. Everyday users do not need to work with debit, credit or ledger codes.</p></div><button onClick={()=>setShowForm(v=>!v)} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-medium"><Plus className="size-4"/>Ledger account</button></div><AccountingNav/>{error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>:null}
  <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Trial balance</h2><p className="mt-1 text-sm text-neutral-500">All posted journal entries should stay balanced.</p></div><span className={`rounded-full px-3 py-1 text-xs font-medium ${balanced?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{balanced?"Balanced":"Needs review"}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-neutral-50 p-4"><p className="text-xs uppercase tracking-wide text-neutral-400">Total debit</p><p className="mt-1 text-xl font-semibold">{money(trial?.total_debit??0)}</p></div><div className="rounded-xl bg-neutral-50 p-4"><p className="text-xs uppercase tracking-wide text-neutral-400">Total credit</p><p className="mt-1 text-xl font-semibold">{money(trial?.total_credit??0)}</p></div></div><div className="mt-4 max-h-80 overflow-auto"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-white"><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Code</th><th className="px-2 py-3">Account</th><th className="px-2 py-3">Debit</th><th className="px-2 py-3">Credit</th></tr></thead><tbody>{trial?.rows.filter(r=>Number(r.debit)||Number(r.credit)).map(r=><tr key={r.ledger_account_id} className="border-b last:border-0"><td className="px-2 py-3 font-mono text-xs">{r.code}</td><td className="px-2 py-3">{r.name}</td><td className="px-2 py-3">{money(r.debit)}</td><td className="px-2 py-3">{money(r.credit)}</td></tr>)}</tbody></table>{!loading&&trial?.rows.every(r=>!Number(r.debit)&&!Number(r.credit))?<p className="py-10 text-center text-sm text-neutral-400">No posted journals yet.</p>:null}</div></div><div className="rounded-2xl border bg-white p-5"><BookOpen className="size-5"/><h2 className="mt-3 font-semibold">Accounting controls</h2><div className="mt-4 space-y-3 text-sm leading-5 text-neutral-500"><p>Posted entries must have equal debit and credit.</p><p>Closed periods reject new postings.</p><p>System account codes are protected.</p><p>Operational screens create accounting records automatically where configured.</p><p>Use reversal instead of deleting posted data.</p></div></div></section>
  <section className="rounded-2xl border bg-white p-5"><div><h2 className="font-semibold">Journal history</h2><p className="mt-1 text-sm text-neutral-500">Trace every posted accounting entry back to its source. Click a row to inspect lines.</p></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Entry</th><th className="px-2 py-3">Date</th><th className="px-2 py-3">Source</th><th className="px-2 py-3">Reference</th><th className="px-2 py-3">Debit</th><th className="px-2 py-3">Credit</th><th className="px-2 py-3"></th></tr></thead><tbody>{journals.map(j=><><tr key={j.id} className="border-b"><td className="px-2 py-3"><button onClick={()=>setExpanded(expanded===j.id?null:j.id)} className="font-medium hover:underline">{j.entry_number}</button></td><td className="px-2 py-3">{j.entry_date}</td><td className="px-2 py-3">{pretty(j.source_type)}</td><td className="px-2 py-3">{j.reference||"—"}</td><td className="px-2 py-3">{money(j.total_debit)}</td><td className="px-2 py-3">{money(j.total_credit)}</td><td className="px-2 py-3 text-right">{j.source_type!=="reversal"?<button disabled={saving} onClick={()=>void reverse(j)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs"><RotateCcw className="size-3.5"/>Reverse</button>:<span className="text-xs text-neutral-400">Reversal</span>}</td></tr>{expanded===j.id?<tr key={`${j.id}-lines`} className="border-b bg-neutral-50"><td colSpan={7} className="p-3"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead><tr className="text-left text-neutral-400"><th className="py-2">Account</th><th>Description</th><th>Currency</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{j.lines.map(line=><tr key={line.id}><td className="py-2">{line.account_code} · {line.account_name}</td><td>{line.description||"—"}</td><td>{line.currency}</td><td>{money(line.debit)}</td><td>{money(line.credit)}</td></tr>)}</tbody></table></div></td></tr>:null}</>)}</tbody></table>{!loading&&!journals.length?<p className="py-10 text-center text-sm text-neutral-400">No journals posted yet.</p>:null}</div></section>
  {showForm?<section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Create ledger account</h2><p className="mt-1 text-sm text-neutral-500">Only use this when your accountant needs a new Chart of Accounts entry.</p><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Account code"><input required value={form.code} onChange={e=>setForm(v=>({...v,code:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><Field label="Account name"><input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><Field label="Category"><select value={form.category} onChange={e=>changeCategory(e.target.value as LedgerAccount["category"])} className="w-full rounded-xl border bg-white px-3 py-2.5">{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></Field><Field label="Subtype"><input value={form.subtype} onChange={e=>setForm(v=>({...v,subtype:e.target.value}))} className="w-full rounded-xl border px-3 py-2.5"/></Field><Field label="Normal balance"><select value={form.normal_balance} onChange={e=>setForm(v=>({...v,normal_balance:e.target.value as "debit"|"credit"}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="debit">Debit</option><option value="credit">Credit</option></select></Field><Field label="Parent account"><select value={form.parent_id} onChange={e=>setForm(v=>({...v,parent_id:e.target.value}))} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">No parent</option>{accounts.filter(a=>a.category===form.category&&a.is_active).map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></Field><div className="md:col-span-2 lg:col-span-3"><button disabled={saving} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving…":"Create ledger account"}</button></div></form></section>:null}
  <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Chart of Accounts</h2><p className="mt-1 text-sm text-neutral-500">System and custom ledger accounts.</p></div><span className="text-sm text-neutral-400">{accounts.length} accounts</span></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-neutral-400"><th className="px-2 py-3">Code</th><th className="px-2 py-3">Name</th><th className="px-2 py-3">Category</th><th className="px-2 py-3">Normal balance</th><th className="px-2 py-3">Type</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-b last:border-0"><td className="px-2 py-3 font-mono text-xs">{a.code}</td><td className="px-2 py-3 font-medium">{a.name}</td><td className="px-2 py-3 capitalize">{a.category}</td><td className="px-2 py-3 capitalize">{a.normal_balance}</td><td className="px-2 py-3 text-neutral-500">{a.is_system?"System":"Custom"}</td></tr>)}</tbody></table></div></section>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm"><span className="mb-1.5 block font-medium text-neutral-600">{label}</span>{children}</label>}
