SYSTEM_ROLE_SUPER_ADMIN = "super_admin"
SYSTEM_ROLE_USER = "user"

MEMBERSHIP_ROLE_ADMIN = "admin"
MEMBERSHIP_ROLE_USER = "user"

MEMBERSHIP_STATUS_ACTIVE = "active"
MEMBERSHIP_STATUS_SUSPENDED = "suspended"

ORGANIZATION_STATUS_ACTIVE = "active"
ORGANIZATION_STATUS_SUSPENDED = "suspended"

SUBSCRIPTION_STATUS_TRIALING = "trialing"
SUBSCRIPTION_STATUS_ACTIVE = "active"
SUBSCRIPTION_STATUS_PAST_DUE = "past_due"
SUBSCRIPTION_STATUS_CANCELED = "canceled"
SUBSCRIPTION_STATUS_SUSPENDED = "suspended"
